;;; Douglas P. Fields, Jr. - symbolics@lisp.engineer
;;; Copyright 2026 Douglas P. Fields, Jr.
;;;
;;; Developed with Antigravity CLI (Gemini 3.5 Flash and 3.1 Pro)
;;;
;;; C# Assembly Lisp Package Generator -- top-level batch generation entry points
;;; Split out of the former assembly-package-generator.lisp (pure internal
;;; reorganization; see doc/generator-design-notes.md).

(in-package :assembly-package-generator)


(defun generate-batch-asd-file (entries-with-resolved output-dir creation-time cli-version child-ancestor-fqs
                                 &optional defgeneric-model (csharp-generic-in-asd t) skip-missing)
  "Writes csharp-assembly-packages.asd into OUTPUT-DIR, listing every
   generated class package (from ENTRIES-WITH-RESOLVED, a list of
   (entry . resolved) pairs as accumulated by
   GENERATE-ASSEMBLY-PACKAGES-BATCH, where ENTRY is a manifest entry with
   :assembly-name and RESOLVED is a list of resolved-class plists -- see
   MAKE-RESOLVED-CLASS) as a :file component, in the same order the classes
   were requested on the command line (with any pulled-in ancestor classes
   appended after their assembly's explicitly-requested ones -- see
   GENERATE-ASSEMBLY-PACKAGES-BATCH). The packages.lisp file written by
   GENERATE-BATCH-PACKAGES-FILE is listed first, with every class :file
   depending on it via :depends-on, since defpackage forms live there
   rather than in the class files. A child with a non-empty
   CHILD-ANCESTOR-FQS entry also depends on each of its ancestor packages,
   so ASDF's own dependency graph reflects the true generation dependency
   (though not strictly required for correctness once the whole system is
   loaded -- see doc/parents-and-interfaces-plan.md).
   CLI-VERSION is the dotcl-packagegen tool's own version string (e.g.
   \"2.20.0\"), used only in the long description; the system's own
   :version is the short generator format version (*GENERATOR-VERSION*).
   DEFGENERIC-MODEL, if non-nil (see COMPUTE-DEFGENERIC-MODEL), also adds
   its own *CSHARP-GENERICS-PACKAGE-NAME* :file component, depending on
   \"packages\", \"csharp-assembly-utils\", and every one of its own
   opted-in classes' package files (must load last -- see
   doc/make-everything-defgeneric.md) -- UNLESS CSHARP-GENERIC-IN-ASD (T by
   default; Program.cs's --csharp-generic-in-asd/--no-csharp-generic-in-asd,
   Version 46) is NIL, in which case that :file form is instead written out
   as a comment, with an explanation that it's meant to be spliced manually
   into the consuming project's own .asd at a point after that project's
   own target assembly is already loaded: #.(dotnet:class-for-type ...)
   inside csharp-generics.lisp resolves types at COMPILE time (Version 41),
   which can fail if this whole generated system is loaded via ASDF
   :depends-on before the consuming project's own assembly is in scope
   (dotcl/dotcl#49) -- the same underlying constraint --ensure-type-in-
   generic (Version 45) works around per-class-registration-order, but this
   flag addresses at the .asd-component level instead. Has no effect when
   DEFGENERIC-MODEL is nil (nothing to comment out). See
   doc/generator-design-notes.md's Version 46 section. SKIP-MISSING (nil by
   default; Program.cs's --skip-missing/--no-skip-missing, the global,
   whole-invocation flag governing whether an unresolvable ancestor is a
   hard error or a dropped warning) is recorded, alongside
   CSHARP-GENERIC-IN-ASD, in a global-flags line in the long description --
   see doc/plan-fable-detail-07.md."
  (let ((output-file (merge-pathnames (make-pathname :name "csharp-assembly-packages" :type "asd")
                                       (pathname (concatenate 'string output-dir "/")))))
    (with-open-file (stream output-file :direction :output :if-exists :supersede :if-does-not-exist :create)
      (format stream ";;; Generated automatically. Do not edit.~%")
      (format stream ";;; Generator Version: ~D~%" *generator-version*)
      (format stream ";;; Creation Date: ~A~%~%" creation-time)
      (format stream "(asdf:defsystem \"csharp-assembly-packages\"~%")
      (format stream "  :author \"DotCL C# Assembly Package Generator\"~%")
      (format stream "  :version \"~D\"~%" *generator-version*)
      (format stream "  :homepage \"https://github.com/LispEngineer/dotcl-package-generator\"~%")
      (format stream "  :description \"Lisp packages enabling ease-of-interoperation with selected C# classes and objects.\"~%")
      (format stream "  :long-description \"~A\"~%"
              (escape-lisp-string
               (with-output-to-string (desc)
                 (format desc "Generated by dotcl-packagegen ~A (package format version ~D)~%"
                         cli-version *generator-version*)
                 (format desc "Generation date: ~A~%" creation-time)
                 (format desc "Global flags: --~:[no-~;~]skip-missing --~:[no-~;~]csharp-generic-in-asd~%~%"
                         skip-missing csharp-generic-in-asd)
                 (format desc "Packages included:~%")
                 (dolist (pair entries-with-resolved)
                   (let ((entry (car pair))
                         (resolved (cdr pair)))
                     (format desc "  ~A~%" (getf entry :assembly-name))
                     (dolist (rc resolved)
                       (let* ((cls (getf rc :class-plist))
                              (cprops (getf rc :constant-properties))
                              (fq-name (getf cls :fully-qualified-name))
                              (pkg-name (type-fq-name-to-pkg-name fq-name)))
                         (format desc "    ~A => ~A~%" fq-name pkg-name)
                         (when cprops
                           (format desc "      Constant properties: ~{~A~^, ~}~%" cprops))
                         (format desc "      Options: ~A~%" (format-class-options-line rc))
                         (when (getf rc :discovered-via)
                           (format desc "      Discovered via: ~A~%" (getf rc :discovered-via))))))))))
      (format stream "  :components (~%")
      (format stream "   (:file \"packages\")~%")
      (format stream "   (:file \"csharp-assembly-utils\" :depends-on (\"packages\"))~%")
      (dolist (pair entries-with-resolved)
        (dolist (rc (cdr pair))
          (let* ((fq-name (getf (getf rc :class-plist) :fully-qualified-name))
                 (pkg-name (type-fq-name-to-pkg-name fq-name))
                 (ancestor-pkg-names (mapcar #'type-fq-name-to-pkg-name
                                              (gethash fq-name child-ancestor-fqs))))
            (format stream "   (:file \"~A\" :depends-on (\"packages\" \"csharp-assembly-utils\"~{ \"~A\"~}))~%"
                    pkg-name ancestor-pkg-names))))
      (when defgeneric-model
        (let ((depends-on-pkgs (mapcar (lambda (c) (getf c :pkg-name)) (getf defgeneric-model :classes))))
          (if csharp-generic-in-asd
              (format stream "   (:file \"~A\" :depends-on (\"packages\" \"csharp-assembly-utils\"~{ \"~A\"~}))~%"
                      *csharp-generics-package-name* depends-on-pkgs)
              (progn
                (format stream "   ;; ~A.lisp is NOT included above as a :components entry~%"
                        *csharp-generics-package-name*)
                (format stream "   ;; (--no-csharp-generic-in-asd): #.(dotnet:class-for-type ...) inside it~%")
                (format stream "   ;; resolves .NET types at COMPILE time, unlike every other file in~%")
                (format stream "   ;; this system, which can fail if this whole system is loaded via~%")
                (format stream "   ;; ASDF :depends-on before the consuming project's own target~%")
                (format stream "   ;; assembly is in scope (see doc/generator-design-notes.md's~%")
                (format stream "   ;; Version 41/46 sections and dotcl/dotcl#49). To use~%")
                (format stream "   ;; --defgeneric-generated dispatch, splice the commented-out~%")
                (format stream "   ;; component below into the CONSUMING project's own .asd~%")
                (format stream "   ;; :components list instead, at a point after its own assembly~%")
                (format stream "   ;; references are already loaded:~%")
                (format stream "   ;; (:file \"~A\" :depends-on (\"packages\" \"csharp-assembly-utils\"~{ \"~A\"~}))~%"
                        *csharp-generics-package-name* depends-on-pkgs)))))
      (format stream "  ))~%"))
    output-file))

(defun generate-assembly-packages-batch (assembly-entries output-dir creation-time cli-version
                                          package-template-path utils-template-path
                                          &optional skip-missing (csharp-generic-in-asd t))
  "Loads each entry's metadata file, resolves all requested classes across
   all entries, and only then generates the .lisp package files, so a
   class name that cannot be found aborts the whole run before anything is
   written. An entry with an empty :classes list is not an error -- it
   means only that entry's metadata file (already written by C#) was
   requested.

   A work queue (Version 39, doc/plan-v38.md's Part B), seeded by every
   explicitly-requested resolved class, recursively discovers related
   classes across all six per-class direction flags (:export-parents/
   :export-interfaces/:export-object upward via EXPAND-RELATED's own
   internal multi-hop ancestor-chain walk; :output-nested/:output-children/
   :output-implementations downward, made transitive by this OUTER queue
   re-invoking EXPAND-RELATED on each newly-discovered class in turn) and
   folds the result into the working set: a newly-discovered class carries
   its discoverer's ENTIRE flag set (all six direction flags plus
   :defgeneric/:extension-methods/:ensure-type/:ensure-type-in-generic, never its
   :constant-properties), so discovery/re-export cascades recursively
   through the whole connected component a flag reaches, UNLESS it was
   ALSO explicitly requested, in which case the explicit request's own
   flags/constant-properties win and no duplicate entry is added. Each
   class discovered this way is appended after its owning assembly's
   explicitly-requested classes (stable, minimal reordering -- see
   doc/parents-and-interfaces-plan.md). Only classes discovered via
   :export-parents/:export-interfaces become a re-export source
   (CHILD-ANCESTOR-FQS) for the class that discovered them; the three
   downward directions only ever add their discoveries to the working set
   as independent packages, never modifying anything's own re-export block.
   An ancestor (from :export-parents/:export-interfaces only -- the
   downward directions have no 'missing' concept) that cannot be resolved
   anywhere is a hard error unless SKIP-MISSING is true, in which case it
   is dropped with a warning instead. A warning is also printed if the
   total number of classes discovered this way is large, since
   :output-children/:output-implementations on a widely-derived base can
   pull in a great many types.

   Before any class file is written, emits packages.lisp
   (GENERATE-BATCH-PACKAGES-FILE, using PACKAGE-TEMPLATE-PATH for the
   CSHARP-ASSEMBLY-UTILS defpackage form) holding every class's defpackage
   form plus the parents/interfaces re-export post-pass, so it exists ahead
   of (and independent of) the per-class files that assume their package is
   already defined. Then emits csharp-assembly-utils.lisp
   (GENERATE-BATCH-UTILS-FILE, using UTILS-TEMPLATE-PATH). Once every class
   file has been written, also independently emits
   *CSHARP-GENERICS-PACKAGE-NAME*.lisp (GENERATE-BATCH-GENERICS-FILE, a
   no-op if no class opted into :defgeneric -- see COMPUTE-DEFGENERIC-MODEL
   and doc/make-everything-defgeneric.md), then finally a
   csharp-assembly-packages.asd tying them all together; CLI-VERSION (the
   dotcl-packagegen tool's own semver, e.g. \"2.20.0\") is used in that
   file's long description. CSHARP-GENERIC-IN-ASD (T by default -- Program.cs's
   --csharp-generic-in-asd/--no-csharp-generic-in-asd, Version 46) is passed
   straight through to GENERATE-BATCH-ASD-FILE, which only consults it when
   a DEFGENERIC-MODEL actually exists: when NIL, csharp-generics.lisp's own
   :file component is written out as a comment instead of an active
   component, since #.(dotnet:class-for-type ...) resolves types at COMPILE
   time (see doc/generator-design-notes.md's Version 41/45 sections), which
   can fail if this whole system is loaded via ASDF :depends-on before the
   consuming project's own target assembly is in scope (dotcl/dotcl#49) --
   the commented-out form is meant to be spliced manually into the
   consuming project's own .asd instead, at a point after that assembly is
   already loaded. csharp-generics.lisp itself is still generated either
   way; only its own .asd entry is affected."
  (let ((entries-with-resolved nil)
        (entry-resolved-table (make-hash-table :test #'eq))
        (all-not-found nil)
        (seen-fq (make-hash-table :test #'equal))
        (child-ancestor-fqs (make-hash-table :test #'equal))
        (index (build-metadata-index assembly-entries)))

    ;; Phase A: resolve every explicitly requested class, per entry, exactly
    ;; as before (unchanged not-found contract: abort before touching
    ;; ancestors or generating anything if any requested class is missing).
    (dolist (entry assembly-entries)
      (multiple-value-bind (resolved not-found) (resolve-batch-entry entry)
        (setf (gethash entry entry-resolved-table) resolved)
        (push entry entries-with-resolved)
        (dolist (rc resolved)
          (setf (gethash (getf (getf rc :class-plist) :fully-qualified-name) seen-fq) t))
        (setf all-not-found (append all-not-found not-found))))
    (setf entries-with-resolved (nreverse entries-with-resolved))

    (when all-not-found
      (dolist (cname all-not-found)
        (utils:format-red *error-output* "Error: Class not found in assembly metadata: ~A~%" cname))
      (error "One or more requested classes were not found: ~{~A~^, ~}" all-not-found))

    ;; Phase B (Version 39, doc/plan-v38.md's Part B): a work queue, seeded
    ;; by every explicitly-requested resolved-class, recursively discovers
    ;; related classes across all six directions (--export-parents/
    ;; --export-interfaces/--export-object upward; --output-nested/
    ;; --output-children/--output-implementations downward) via
    ;; EXPAND-RELATED. Every newly-discovered class is enqueued carrying
    ;; its discoverer's ENTIRE per-class flag set (all six export-*/output-*
    ;; flags plus --defgeneric/--extension-methods/--ensure-type/
    ;; --ensure-type-in-generic, but
    ;; never its discoverer's --constant-properties, which names properties
    ;; specific to one class), so discovery/re-export cascades recursively
    ;; through the whole connected component a flag reaches -- see PLAN.md's
    ;; "Recursive Related-Class Discovery" section. Only each class's own
    ;; ANCESTOR-DISCOVERED (--export-parents/--export-interfaces) is
    ;; recorded as a re-export source (child-ancestor-fqs); DOWNWARD-
    ;; DISCOVERED (--output-nested/--output-children/--output-
    ;; implementations) is added to the working set ONLY -- never a
    ;; re-export source, and never modifies the discovering class's own
    ;; package (see EXPAND-RELATED's docstring for why this asymmetry is
    ;; correct).
    (let ((all-missing nil)
          (discovery-additions (make-hash-table :test #'eq))
          (total-discovered 0)
          (queue nil))
      (multiple-value-bind (subclass-index implementer-index) (build-reverse-indexes index)
        (dolist (entry entries-with-resolved)
          (dolist (rc (gethash entry entry-resolved-table))
            (setf queue (nconc queue (list rc)))))
        (loop while queue
              do (let* ((rc (pop queue))
                        (self-fq (getf (getf rc :class-plist) :fully-qualified-name)))
                   (multiple-value-bind (ancestor-discovered downward-discovered missing)
                       (expand-related (getf rc :class-plist)
                                        (getf rc :export-parents)
                                        (getf rc :export-interfaces)
                                        (getf rc :export-object)
                                        (getf rc :output-nested)
                                        (getf rc :output-children)
                                        (getf rc :output-implementations)
                                        index subclass-index implementer-index)
                     (setf all-missing (append all-missing missing))
                     (when ancestor-discovered
                       (setf (gethash self-fq child-ancestor-fqs)
                             (mapcar (lambda (pair) (getf (car pair) :fully-qualified-name))
                                     ancestor-discovered)))
                     (flet ((enqueue-discovered (pair discovered-via)
                              (let* ((discovered-plist (car pair))
                                     (owning-entry (cdr pair))
                                     (discovered-fq (getf discovered-plist :fully-qualified-name)))
                                (unless (gethash discovered-fq seen-fq)
                                  (setf (gethash discovered-fq seen-fq) t)
                                  (incf total-discovered)
                                  (let ((new-rc (make-resolved-class
                                                 discovered-plist nil
                                                 (getf rc :export-parents) (getf rc :export-interfaces)
                                                 (getf rc :export-object)
                                                 (getf rc :defgeneric)
                                                 (getf rc :extension-methods)
                                                 (getf rc :output-nested) (getf rc :output-children)
                                                 (getf rc :output-implementations)
                                                 (getf rc :ensure-type) (getf rc :ensure-type-in-generic)
                                                 discovered-via)))
                                    (push new-rc (gethash owning-entry discovery-additions))
                                    (setf queue (nconc queue (list new-rc))))))))
                       ;; DISCOVERED-VIA (doc/plan-fable-detail-07.md) records
                       ;; provenance for the generated packages.lisp/per-class
                       ;; file header ";;; Discovered via:" comment: which of
                       ;; RC's own direction flags produced this discovery
                       ;; (ancestor-discovered can only come from
                       ;; --export-parents/--export-interfaces; downward-
                       ;; discovered only from --output-nested/--output-
                       ;; children/--output-implementations), and RC's own
                       ;; fully-qualified-name as the discoverer. When RC has
                       ;; more than one relevant flag set, all of them are
                       ;; listed -- EXPAND-RELATED's internal walk does not
                       ;; separately tag which single flag found which class.
                       (when ancestor-discovered
                         (let ((via (format nil "~{~A~^/~} from ~A"
                                            (append (and (getf rc :export-parents) (list "--export-parents"))
                                                    (and (getf rc :export-interfaces) (list "--export-interfaces")))
                                            self-fq)))
                           (dolist (pair ancestor-discovered)
                             (enqueue-discovered pair via))))
                       (when downward-discovered
                         (let ((via (format nil "~{~A~^/~} from ~A"
                                            (append (and (getf rc :output-nested) (list "--output-nested"))
                                                    (and (getf rc :output-children) (list "--output-children"))
                                                    (and (getf rc :output-implementations) (list "--output-implementations")))
                                            self-fq)))
                           (dolist (pair downward-discovered)
                             (enqueue-discovered pair via))))))))

        (when (> total-discovered 200)
          (format *error-output*
                  "Warning: related-class discovery (--export-parents/--export-interfaces/--output-nested/--output-children/--output-implementations) pulled in ~D additional classes across this batch -- generation may take a while and/or produce a very large package set.~%"
                  total-discovered)))

      (when all-missing
        (if skip-missing
            (dolist (entry all-missing)
              (format *error-output* "Warning: Ancestor class not found in any provided assembly metadata (skipped): ~A (required by ~A)~%"
                      (car entry) (cdr entry)))
            (progn
              (dolist (entry all-missing)
                (utils:format-red *error-output* "Error: Ancestor class not found in any provided assembly metadata: ~A (required by ~A)~%"
                                   (car entry) (cdr entry)))
              (error "One or more required ancestor classes were not found (pass --skip-missing to ignore): ~{~A~^, ~}"
                     (mapcar #'car all-missing)))))

      ;; Merge: each entry's final resolved list is its explicit classes
      ;; (already in request order) followed by any newly-discovered
      ;; classes, in first-discovered order.
      (dolist (entry entries-with-resolved)
        (let ((additions (nreverse (gethash entry discovery-additions))))
          (when additions
            (setf (gethash entry entry-resolved-table)
                  (append (gethash entry entry-resolved-table) additions))))))

    (let* ((entries-with-resolved-pairs
             (mapcar (lambda (entry) (cons entry (gethash entry entry-resolved-table)))
                     entries-with-resolved))
           (all-resolved (loop for pair in entries-with-resolved-pairs append (cdr pair)))
           (extension-index (build-extension-method-index index)))

      ;; Phase C: for every resolved class that opted into :extension-methods,
      ;; compute and store its matched/skipped extension-method wrappers
      ;; (Version 38, doc/plan-v38.md) -- done before defgeneric-model/
      ;; packages.lisp/class-file generation below, all of which need to see
      ;; a class's :matched-extensions to stay in sync (compute-package-
      ;; exports-and-shadows/collect-class-instance-generics/generate-class-
      ;; file all take it as an argument read from the resolved-class plist).
      (dolist (rc all-resolved)
        (when (getf rc :extension-methods)
          (multiple-value-bind (survivors skipped)
              (compute-matched-extensions-for-class (getf rc :class-plist)
                                                     (getf rc :constant-properties)
                                                     extension-index)
            (setf (getf rc :matched-extensions) survivors)
            (setf (getf rc :skipped-extensions) skipped))))

      (let* ((defgeneric-model (compute-defgeneric-model all-resolved)))

        (generate-batch-packages-file entries-with-resolved-pairs output-dir creation-time
                                       package-template-path child-ancestor-fqs
                                       defgeneric-model)
        (generate-batch-utils-file output-dir creation-time utils-template-path)

        (dolist (rc all-resolved)
          (let ((cls (getf rc :class-plist))
                (cprops (getf rc :constant-properties)))
            (format *error-output* "Generating package for C# Class: ~A~%" (getf cls :fully-qualified-name))
            (generate-class-file cls output-dir cprops creation-time
                                  (getf rc :matched-extensions) (getf rc :skipped-extensions)
                                  (getf rc :ensure-type)
                                  (format-class-options-line rc) (getf rc :discovered-via))))

        (generate-batch-generics-file output-dir creation-time defgeneric-model)

        (generate-batch-asd-file entries-with-resolved-pairs output-dir creation-time cli-version
                                  child-ancestor-fqs defgeneric-model csharp-generic-in-asd skip-missing)))

    t))

(defun run-assembly-package-generator-batch (manifest-file output-dir creation-time cli-version
                                              package-template-path utils-template-path
                                              &optional skip-missing (csharp-generic-in-asd t))
  "CLI entry point called by DotclHost.Call for the single-pass generator.
   MANIFEST-FILE is a Lisp-reader-compatible list of plists, one per
   assembly:
     ((:metadata-file \"...\" :assembly-name \"...\"
       :classes ((:name \"...\" :constant-properties \"...\"
                  :export-parents t/nil :export-interfaces t/nil
                  :export-object t/nil :defgeneric t/nil
                  :extension-methods t/nil
                  :output-nested t/nil :output-children t/nil
                  :output-implementations t/nil :ensure-type t/nil
                  :ensure-type-in-generic t/nil) ...)) ...)
   :output-nested/:output-children/:output-implementations (per-class,
   Version 39, doc/plan-v38.md's Part B) discover, respectively, every type
   nested inside a class, every direct-or-indirect subclass of a class, and
   every implementer of a class (when it is an interface), adding each as
   its own generated package -- see GENERATE-ASSEMBLY-PACKAGES-BATCH's work
   queue and EXPAND-RELATED.
   :defgeneric (per-class, resolved from Program.cs's
   --defgeneric/--enable-defgeneric flags) opts a class's instance methods
   and instance property/field accessors into the shared
   *CSHARP-GENERICS-PACKAGE-NAME* package of unified CLOS generic functions
   dispatching on C# runtime type via #.(dotnet:class-for-type ...)
   (DotCL 0.1.17+) -- see COMPUTE-DEFGENERIC-MODEL and
   doc/make-everything-defgeneric.md.
   :extension-methods (per-class, resolved from Program.cs's
   --extension-methods/--enable-extension-methods, ON by default) opts a
   class into having matching C# extension methods (exact concrete
   'this'-type match only) injected as obj!-first wrappers -- see
   COMPUTE-MATCHED-EXTENSIONS-FOR-CLASS and doc/plan-v38.md.
   :ensure-type (per-class, resolved from Program.cs's
   --ensure-type/--no-ensure-type, OFF by default) opts a class into
   emitting the \"Register C# Type with CLOS\" eval-when
   (EnsureDotNetTypeClass) that Version 43 and earlier always emitted
   unconditionally -- see EMIT-TYPE-CONSTANTS-AND-CLOS-REGISTRATION and
   doc/generator-design-notes.md's Version 44 section.
   PACKAGE-TEMPLATE-PATH/UTILS-TEMPLATE-PATH point at
   csharp-assembly-utils-package.template.lisp /
   csharp-assembly-utils.template.lisp, copied next to the executable.
   SKIP-MISSING (a Lisp boolean, passed as a plain scalar rather than
   folded into the manifest since it is a single global flag) governs
   whether an unresolvable parent/interface ancestor is a hard error
   (default/NIL) or a dropped-with-a-warning (T) -- see
   GENERATE-ASSEMBLY-PACKAGES-BATCH / EXPAND-ANCESTORS.
   CSHARP-GENERIC-IN-ASD (also a plain scalar, T by default; Program.cs's
   --csharp-generic-in-asd/--no-csharp-generic-in-asd, Version 46) is
   passed straight through to GENERATE-ASSEMBLY-PACKAGES-BATCH /
   GENERATE-BATCH-ASD-FILE -- see its own docstring for the full rationale.
   Maps string parameters safely and reports errors in red."
  (handler-case
      (let ((mfile (and manifest-file (> (length manifest-file) 0) manifest-file))
            (odir (and output-dir (> (length output-dir) 0) output-dir)))
        (unless mfile
          (error "Manifest file path is required."))
        (unless odir
          (error "Output directory path is required."))
        (unless (probe-file mfile)
          (error "Manifest file not found: ~A" mfile))
        (unless (probe-file package-template-path)
          (error "csharp-assembly-utils package template not found: ~A" package-template-path))
        (unless (probe-file utils-template-path)
          (error "csharp-assembly-utils template not found: ~A" utils-template-path))
        (let ((assembly-entries (utils:safe-read-form-from-file mfile)))
          (generate-assembly-packages-batch assembly-entries odir creation-time cli-version
                                             package-template-path utils-template-path skip-missing
                                             csharp-generic-in-asd)))
    (error (c)
      (utils:format-red *error-output* "Error in assembly-package-generator: ~A~%" c)
      (error c))))
