;;; Douglas P. Fields, Jr. - symbolics@lisp.engineer
;;; Copyright 2026 Douglas P. Fields, Jr.
;;;
;;; Developed with Antigravity CLI (Gemini 3.5 Flash and 3.1 Pro)
;;;
;;; C# Assembly Lisp Package Generator
;;;
;;; This module parses metadata generated by AssemblyToLispy and produces
;;; Common Lisp source files mapping C# classes to Lisp packages.

(in-package :assembly-package-generator)

(defparameter *generator-version* 20
  "Integer version number for the generated Lisp source files.
   Version history:
   1 - Initial generator mapping C# classes to Lisp packages.
   2 - Added symbol-macro support for C# static properties/fields and Lisp symbol shadowing.
   3 - Refined constant property determination.
   4 - Added operator overloading name mapping (e.g. mapping op_Multiply to *).
   5 - Added CLOS class registration support and mapped C# inequality operator to not=.
   6 - Added support for treating selected read-only static properties as constants via configuration.
   7 - Eliminated duplicate exports and shadows in generated package files.
   8 - Mapped implicit and explicit conversion operators and filtered exports to exclude undefined members.
   9 - Added instance property accessors and mutators.
   10 - Added method overload handling with classification into clean vs dirty overloads,
        type-suffixed naming for multi-overload methods, passthrough &rest functions,
        typed-call optimization for value type receivers, and dirty overload documentation.
   11 - Added support for C# constructors (new) with overload dispatch and struct parameterless constructor injection.
   12 - Added support for C# generic methods of exactly one type argument using dotnet:invoke-generic and dotnet:static-generic.
   13 - Refactored C# overloaded operator passthrough generation to dispatch based on argument types and counts in Lisp, avoiding MissingMethodExceptions.
   14 - Qualified standard Common Lisp comparison function cl:= in emitted passthrough code, preventing it from resolving to the shadowed = operator of the generated package.
   15 - Protected critical Lisp syntax symbols (quote, function, t, nil) from being shadowed by mapping conflicting C# member names to quote!, function!, t!, nil!; qualified other standard Common Lisp symbols in generated templates with cl: prefix.
   16 - Tracked is-static-overload-p per clean method overload inside Case 3 (instead of using group-wide static-p) to ensure overloaded static methods are correctly generated as static wrappers.
   17 - Mapped C# field/property 'NaN' to Lisp 'nan' in camel-to-kebab; mapped 'IsSomething' methods/properties to 'something?' in map-member-name.
   18 - Added Master Wrapper with Precise Dispatch using Lisp's &key (var init supplied-p) syntax, split static vs instance mixed-mode overloads using '*' suffix, and added csharp-overload-not-found condition.
   19 - Nested C# type names (CIL '+' separator, e.g. Outer+Inner) are now flattened to the same hyphen convention as namespace dots when deriving a type's Lisp package/file name (new type-fq-name-to-pkg-name helper), instead of leaking a literal '+' into it; camel-to-kebab itself is untouched (it is also applied to already-mapped operator names like the literal '+' produced for C#'s op_Addition, which must not be altered), and :fully-qualified-name plus all reflection-facing uses remain unaffected.
   20 - Open-generic type names (.NET's backtick arity suffix, e.g. Dictionary`2 or ``Action`4``) are now also flattened to '-' in type-fq-name-to-pkg-name, alongside '+'; a raw backtick left in a generated package/symbol name was read by the Lisp reader as the backquote macro character, silently corrupting the surrounding defpackage form instead of signaling an error.")

(defun camel-to-kebab (name)
  "Convert a PascalCase/camelCase string to Lisp kebab-case.
   Also maps dot characters '.' to hyphens '-'."
  (if (string= name "NaN")
      "nan"
      (let ((len (length name)))
        (with-output-to-string (sb)
          (loop for i from 0 to (1- len)
                for c = (char name i)
                do (cond
                     ((char= c #\.)
                      (write-char #\- sb))
                     ((upper-case-p c)
                      (when (and (> i 0)
                                 (char/= (char name (1- i)) #\-)
                                 (char/= (char name (1- i)) #\.)
                                 (or (not (upper-case-p (char name (1- i))))
                                     (and (< (1+ i) len)
                                          (lower-case-p (char name (1+ i))))))
                        (write-char #\- sb))
                      (write-char (char-downcase c) sb))
                     (t
                      (write-char c sb))))))))

(defun type-fq-name-to-pkg-name (fq-name)
  "Converts a type's fully-qualified-name to a Lisp package/file name.
   fq-name may contain two CLR-native characters that must NOT be touched
   by camel-to-kebab itself (that function is also applied to
   already-mapped member/operator names, which legitimately reuse some of
   these characters):
   - '+', CIL's nested-type separator (e.g. Outer+Inner). The C# '+'
     operator (op_Addition) is mapped to the literal one-character Lisp
     name \"+\" upstream in AssemblyToLispy.cs, so a blanket '+' handling
     inside camel-to-kebab would corrupt operator overload wrappers.
   - '`', .NET's open-generic-type arity suffix (e.g. Dictionary`2,
     ``Action`4``). A raw backtick in a generated symbol/package name is
     read by the Lisp reader as the backquote macro character rather than
     a literal character, corrupting the surrounding form (unlike '+',
     backtick has no legitimate use in any member/operator name, but the
     substitution still belongs here rather than in camel-to-kebab to keep
     all type-name sanitization in one place).
   Both are flattened to '-' (matching the existing '.' convention) only
   here, on a type's own fully-qualified name, before camel-casing the
   rest."
  (camel-to-kebab (substitute #\- #\` (substitute #\- #\+ fq-name))))

(defun split-string (string &optional (separator #\;))
  "Split a string into a list of substrings at occurrences of the separator character."
  (let ((result nil)
        (start 0)
        (len (length string)))
    (loop for i from 0 to (1- len)
          do (when (char= (char string i) separator)
               (push (subseq string start i) result)
               (setf start (1+ i))))
    (when (<= start len)
      (push (subseq string start len) result))
    (nreverse result)))

(defun map-param-name (name)
  "Convert a C# parameter name to a safe Lisp parameter name,
   renaming reserved words where necessary."
  (let ((kebab (camel-to-kebab name)))
    (cond
      ((string= kebab "t") "t-val")
      ((string= kebab "nil") "nil-val")
      (t kebab))))

(defun map-member-name (name)
  "Convert a Pascal/camel C# member name to a kebab-case Lisp name,
   renaming critical Common Lisp symbols to avoid shadowing them,
   converting IsSomething to something?, and handling NaN."
  (let* ((kebab (cond
                  ((and (uiop:string-prefix-p "Is" name)
                        (> (length name) 2)
                        (upper-case-p (char name 2)))
                   (format nil "~A?" (camel-to-kebab (subseq name 2))))
                  (t (camel-to-kebab name)))))
    (cond
      ((string= kebab "quote") "quote!")
      ((string= kebab "function") "function!")
      ((string= kebab "t") "t!")
      ((string= kebab "nil") "nil!")
      (t kebab))))

(defun escape-lisp-string (str)
  "Escapes double quotes and backslashes in a string for safe output within Lisp strings."
  (with-output-to-string (out)
    (loop for c across str
          do (cond
               ((char= c #\") (write-string "\\\"" out))
               ((char= c #\\) (write-string "\\\\" out))
               (t (write-char c out))))))

(defun get-iso-8601-time ()
  "Get the current UTC time formatted as an ISO 8601 string."
  (multiple-value-bind (second minute hour date month year day-of-week daylight-saving-p time-zone)
      (decode-universal-time (get-universal-time) 0)
    (declare (ignore day-of-week daylight-saving-p time-zone))
    (format nil "~4,'0D-~2,'0D-~2,'0DT~2,'0D:~2,'0D:~2,'0DZ"
            year month date hour minute second)))

(defun literal-field-p (field)
  "Checks if a field plist defines a static literal/constant field."
  (and (getf field :static)
       (getf field :literal)))

(defun runtime-readonly-field-p (field)
  "Checks if a field plist defines a static init-only field that is not literal."
  (and (getf field :static)
       (getf field :init-only)
       (not (getf field :literal))))

(defun constant-property-p (prop)
  "Checks if a property plist defines a static read-only property."
  (and (getf prop :static)
       (getf prop :readable)
       (not (getf prop :writeable))))

(defun instance-property-p (prop)
  "Checks if a property plist defines an instance property."
  (not (getf prop :static)))

(defun static-method-p (method)
  "Checks if a method plist defines a static method."
  (getf method :is-static))

(defun public-instance-field-p (field)
  "Checks if a field plist defines a public instance field."
  (and (not (getf field :static))
       (getf field :public)))


(defun generic-type-p (type-str)
  "Checks if a C# type signature string represents an uninstantiated generic type parameter (contains an exclamation point)."
  (and type-str (find #\! type-str)))

(defun simple-method-p (method all-methods)
  "Returns t if the method qualifies for Phase 1 compilation.
   Criteria:
   - No overloads (exactly one method signature with this name in the class).
   - No generic parameters/return type (or exactly one generic type argument).
   - No default parameter values.
   - No special parameter modifiers (ref, out, ref-readonly, params).
   - No operator overloads.
   - No property accessors (get_/set_)."
  (let* ((name (getf method :name))
         (params (getf method :parameters))
         (static-p (getf method :is-static))
         (is-generic (getf method :is-generic))
         (arity (getf method :generic-arity)))
    (declare (ignore static-p))
    (and name
         ;; Exclude operators and property accessors
         (not (uiop:string-prefix-p "op_" name))
         (not (uiop:string-prefix-p "get_" name))
         (not (uiop:string-prefix-p "set_" name))
         ;; Check for no overloads in the class
         (= 1 (count name all-methods :key (lambda (m) (getf m :name)) :test #'string=))
         ;; Only support generic methods if they have exactly one type argument
         (or (not is-generic) (eql arity 1))
         ;; Check return type for generic markers
         (not (generic-type-p (getf method :return-type)))
         ;; Check all parameters
         (every (lambda (p)
                  (and (not (getf p :has-default))
                       (not (getf p :out))
                       (not (getf p :ref))
                       (not (getf p :ref-readonly))
                       (not (getf p :params))
                       (not (generic-type-p (getf p :type)))))
                 params))))

(defun clean-method-p (method)
  "Returns t if the method is 'clean' (no ref/out/params/defaults/generics).
   Unlike simple-method-p, this does NOT check for uniqueness of the method name,
   allowing it to be used for overloaded methods."
  (let* ((name (getf method :name))
         (params (getf method :parameters))
         (is-generic (getf method :is-generic))
         (arity (getf method :generic-arity)))
    (and name
         (not (uiop:string-prefix-p "op_" name))
         (not (uiop:string-prefix-p "get_" name))
         (not (uiop:string-prefix-p "set_" name))
         ;; Only support generic methods if they have exactly one type argument
         (or (not is-generic) (eql arity 1))
         (not (generic-type-p (getf method :return-type)))
         (every (lambda (p)
                  (and (not (getf p :out))
                       (not (getf p :ref))
                       (not (getf p :ref-readonly))
                       (not (getf p :params))
                       (not (generic-type-p (getf p :type)))))
                params))))

(defun dirty-method-p (method)
  "Returns t if the method has any special parameter modifiers (ref, out, params, or defaults).
   Complement to clean-method-p; a method may be neither clean nor dirty
   if it is an operator or accessor."
  (let ((params (getf method :parameters)))
    (some (lambda (p)
            (or (getf p :has-default)
                (getf p :out)
                (getf p :ref)
                (getf p :ref-readonly)
                (getf p :params)))
          params)))

(defun simple-type-name (full-type-name)
  "Extract the simple (unqualified) type name from a fully qualified C# type name.
   e.g., \"Microsoft.Xna.Framework.Vector2\" => \"Vector2\"
         \"System.Single\" => \"Single\"
         \"System.Collections.Generic.List`1\" => \"List\""
  (let* ((dot-pos (or (position #\. full-type-name :from-end t) -1))
         (base-name (subseq full-type-name (1+ dot-pos)))
         (backtick-pos (position #\` base-name)))
    (if backtick-pos
        (subseq base-name 0 backtick-pos)
        base-name)))

(defun method-overload-name (method)
  "Generate a disambiguated Lisp function name for an overloaded method,
   by appending kebab-cased simple parameter type names.
   e.g., Contains(Vector2) => \"contains-vector-2\"
         DistanceSquared(Vector2, Vector2) => \"distance-squared-vector-2-vector-2\""
  (let* ((base-name (map-member-name (getf method :name)))
         (params (getf method :parameters))
         (type-suffixes (mapcar (lambda (p)
                                  (camel-to-kebab (simple-type-name (getf p :type))))
                                params)))
    (if type-suffixes
        (format nil "~A-~{~A~^-~}" base-name type-suffixes)
        base-name)))

(defun method-signature-str (method)
  "Return a human-readable signature string for a method, e.g.
   'Contains(ref Rectangle, out bool) -> void'."
  (let* ((name (getf method :name))
         (return-type (simple-type-name (or (getf method :return-type) "void")))
         (params (getf method :parameters))
         (param-strs (mapcar (lambda (p)
                               (let ((modifier-str (cond
                                                     ((getf p :ref) "ref ")
                                                     ((getf p :out) "out ")
                                                     ((getf p :params) "params ")
                                                     (t "")))
                                     (type-str (simple-type-name (getf p :type))))
                                 (format nil "~A~A" modifier-str type-str)))
                             params)))
    (format nil "~A(~{~A~^, ~}) -> ~A" name param-strs return-type)))

(defun clean-constructor-p (ctor)
  "Returns t if the constructor is 'clean' (no ref/out/params/defaults/generics)."
  (let ((params (getf ctor :parameters)))
    (every (lambda (p)
             (and (not (getf p :has-default))
                  (not (getf p :out))
                  (not (getf p :ref))
                  (not (getf p :ref-readonly))
                  (not (getf p :params))
                  (not (generic-type-p (getf p :type)))))
           params)))

(defun dirty-constructor-p (ctor)
  "Returns t if the constructor has any special parameter modifiers (ref, out, params, or defaults)."
  (let ((params (getf ctor :parameters)))
    (some (lambda (p)
            (or (getf p :has-default)
                (getf p :out)
                (getf p :ref)
                (getf p :ref-readonly)
                (getf p :params)))
          params)))

(defun constructor-overload-name (ctor)
  "Generate a disambiguated Lisp function name for an overloaded constructor,
   by appending kebab-cased simple parameter type names.
   e.g., ctor(float, float) => \"new-single-single\""
  (let* ((params (getf ctor :parameters))
         (type-suffixes (mapcar (lambda (p)
                                  (camel-to-kebab (simple-type-name (getf p :type))))
                                params)))
    (if type-suffixes
        (format nil "new-~{~A~^-~}" type-suffixes)
        "new")))

(defun constructor-signature-str (ctor)
  "Return a human-readable signature string for a constructor, e.g.
   'new(ref Rectangle, out bool)'."
  (let* ((params (getf ctor :parameters))
         (param-strs (mapcar (lambda (p)
                               (let ((modifier-str (cond
                                                     ((getf p :ref) "ref ")
                                                     ((getf p :out) "out ")
                                                     ((getf p :params) "params ")
                                                     (t "")))
                                     (type-str (simple-type-name (getf p :type))))
                                 (format nil "~A~A" modifier-str type-str)))
                             params)))
    (format nil "new(~{~A~^, ~})" param-strs)))

(defun build-docstring (summary returns parameters doc-plist)
  "Builds a formatted docstring from documentation elements."
  (with-output-to-string (out)
    (when (and summary (> (length summary) 0))
      (format out "Summary: ~A~%" summary))
    (when (and returns (> (length returns) 0))
      (format out "Returns: ~A~%" returns))
    (when (and parameters doc-plist)
      (let ((doc-params (getf doc-plist :parameters)))
        (format out "Parameters:~%")
        (dolist (p parameters)
          (let* ((pname (getf p :name))
                 (ptype (getf p :type))
                 (pdoc (find pname doc-params :key (lambda (dp) (getf dp :name)) :test #'string=))
                 (pdesc (if pdoc (getf pdoc :description) "")))
            (format out "  - ~A (~A): ~A~%"
                    (map-param-name pname)
                    ptype
                    pdesc)))))))

(defun format-param-type-check (param-type arg-str)
  "Returns a Lisp type checking expression string for the given C# parameter type."
  (cond
    ((member param-type '("System.Double" "System.Single" "System.Int32" "System.Int64" "System.Int16" "System.Byte" "System.Decimal") :test #'string=)
     (format nil "(cl:numberp ~A)" arg-str))
    ((string= param-type "System.Boolean")
     (format nil "(cl:typep ~A 'cl:boolean)" arg-str))
    ((string= param-type "System.String")
     (format nil "(cl:stringp ~A)" arg-str))
    (t
     (format nil "(cl:or (cl:null ~A) (monoutils:dotnet-p ~A))" arg-str arg-str))))

(cl:defun complex-group-p (clean-methods)
  "Returns t if the group of clean methods requires a master wrapper dispatch (either multiple overloads or presence of default arguments)."
  (cl:or (cl:>= (cl:length clean-methods) 2)
         (cl:some (cl:lambda (m)
                    (cl:some (cl:lambda (p) (cl:getf p :has-default)) (cl:getf m :parameters)))
                  clean-methods)))

(cl:defun collect-key-params (methods prefix-len)
  "Collects the union of all keyword parameters from methods beyond prefix-len."
  (cl:let ((key-params nil))
    (cl:dolist (m methods)
      (cl:let ((params (cl:nthcdr prefix-len (cl:getf m :parameters))))
        (cl:dolist (p params)
          (cl:let* ((pname (cl:getf p :name))
                    (existing (cl:find pname key-params :key (cl:lambda (kp) (cl:getf kp :name)) :test #'cl:string=)))
            (cl:unless existing
              (cl:push p key-params))))))
    (cl:nreverse key-params)))

(cl:defun find-parameter-default-str (pname methods)
  "Locates the C# default value of parameter pname across methods and returns it as a Lisp expression string."
  (cl:dolist (m methods)
    (cl:let ((p (cl:find pname (cl:getf m :parameters) :key (cl:lambda (param) (cl:getf param :name)) :test #'cl:string=)))
      (cl:when (cl:and p (cl:getf p :has-default))
        (cl:return (cl:getf p :default-value)))))
  "cl:nil")

(cl:defun common-parameter-prefix (methods)
  "Determines the maximum common positional parameter prefix across methods based on lack of default values."
  (cl:let* ((param-lists (cl:mapcar (cl:lambda (m) (cl:getf m :parameters)) methods))
            (min-len (cl:reduce #'cl:min (cl:mapcar #'cl:length param-lists)))
            (prefix nil))
    (cl:loop for idx from 0 to (cl:1- min-len) do
      (cl:let* ((first-param (cl:nth idx (cl:first param-lists)))
                ;; A parameter cannot be positional if it has a default value in any overload.
                (no-default-p (cl:every (cl:lambda (pl)
                                          (cl:let ((p (cl:nth idx pl)))
                                            (cl:not (cl:getf p :has-default))))
                                        param-lists)))
        (cl:if no-default-p
            (cl:push first-param prefix)
            (cl:loop-finish))))
    (cl:nreverse prefix)))

(cl:defun max-mandatory-parameter-len (methods)
  "Returns the maximum number of mandatory parameters (parameters without defaults) in any single overload."
  (cl:let ((max-len 0))
    (cl:dolist (m methods)
      (cl:let* ((params (cl:getf m :parameters))
                (mandatory-count
                  (cl:loop for p in params
                           for idx from 0
                           while (cl:not (cl:getf p :has-default))
                           count t)))
        (cl:setf max-len (cl:max max-len mandatory-count))))
    max-len))

(cl:defun collect-optional-positional-params (methods prefix-len max-mand-len)
  "Collects parameter descriptors for optional positional parameters from index prefix-len to max-mand-len."
  (cl:let ((opt-params nil))
    (cl:loop for idx from prefix-len to (cl:1- max-mand-len) do
      (cl:let ((found-param nil))
        (cl:dolist (m methods)
          (cl:let ((params (cl:getf m :parameters)))
            (cl:when (cl:< idx (cl:length params))
              (cl:setf found-param (cl:nth idx params))
              (cl:return))))
        (cl:when found-param
          (cl:push found-param opt-params))))
    (cl:nreverse opt-params)))

(cl:defun format-master-overload-condition (cm prefix opt-params key-params)
  "Generates Lisp conditional test expression checking supplied-p flags and parameter types for cm."
  (cl:let* ((cond-parts nil)
            (cm-params (cl:getf cm :parameters))
            (prefix-len (cl:length prefix))
            (max-mand-len (+ prefix-len (cl:length opt-params))))
    ;; 1. Check positional prefix types by position index
    (cl:loop for pp in prefix
             for idx from 0 do
      (cl:let* ((lpname (map-param-name (cl:getf pp :name)))
                (cm-p (cl:nth idx cm-params))
                (type-check (format-param-type-check (cl:getf cm-p :type) lpname)))
        (cl:push type-check cond-parts)))
    ;; 2. Check optional positional parameters presence and types
    (cl:loop for op in opt-params
             for idx from prefix-len to (cl:1- max-mand-len) do
      (cl:let* ((op-name (map-param-name (cl:getf op :name)))
                (supplied-var (cl:format nil "supplied-~A" op-name))
                (cm-p (cl:nth idx cm-params)))
        (cl:if cm-p
            (cl:progn
              (cl:push supplied-var cond-parts)
              (cl:push (format-param-type-check (cl:getf cm-p :type) op-name) cond-parts))
            (cl:push (cl:format nil "(cl:not ~A)" supplied-var) cond-parts))))
    ;; 3. Check keyword parameters presence and types
    (cl:dolist (kp key-params)
      (cl:let* ((pname (cl:getf kp :name))
             (lpname (map-param-name pname))
             (supplied-var (cl:format nil "supplied-~A" lpname))
             (cm-p (cl:find pname cm-params :key (cl:lambda (p) (cl:getf p :name)) :test #'cl:string=)))
        (cl:if cm-p
            (cl:progn
              (cl:unless (cl:getf cm-p :has-default)
                (cl:push supplied-var cond-parts))
              (cl:push (format-param-type-check (cl:getf cm-p :type) lpname) cond-parts))
            (cl:push (cl:format nil "(cl:not ~A)" supplied-var) cond-parts))))
    (cl:format nil "(cl:and ~{~A~^ ~})" (cl:nreverse cond-parts))))

(cl:defun format-master-overload-action (cm fq-name name static-p is-generic-p prefix opt-params)
  "Generates C# invocation code for cm, mapping parameter names to the master wrapper's bound variables."
  (cl:let* ((cm-params (cl:getf cm :parameters))
            (prefix-len (cl:length prefix))
            (max-mand-len (+ prefix-len (cl:length opt-params)))
            (param-names
              (cl:loop for p in cm-params
                       for idx from 0
                       collect (cl:cond
                                 ((cl:< idx prefix-len)
                                  (map-param-name (cl:getf (cl:nth idx prefix) :name)))
                                 ((cl:< idx max-mand-len)
                                  (map-param-name (cl:getf (cl:nth (- idx prefix-len) opt-params) :name)))
                                 (cl:t
                                  (map-param-name (cl:getf p :name))))))
            (dotnet-method-name (cl:or (cl:getf cm :mangled-name) name)))
    (cl:cond
      ((cl:and static-p is-generic-p)
       (cl:format nil "(dotnet:static-generic <type-str> \"~A\" (cl:list type)~@[ ~{~A~^ ~}~])" dotnet-method-name param-names))
      (static-p
       (cl:format nil "(dotnet:static <type-str> \"~A\"~@[ ~{~A~^ ~}~])" dotnet-method-name param-names))
      (is-generic-p
       (cl:format nil "(dotnet:invoke-generic (cl:the (dotnet \"~A\") obj) \"~A\" (cl:list type)~@[ ~{~A~^ ~}~])" fq-name dotnet-method-name param-names))
      (cl:t
       (cl:format nil "(dotnet:invoke (cl:the (dotnet \"~A\") obj) \"~A\"~@[ ~{~A~^ ~}~])" fq-name dotnet-method-name param-names)))))

(cl:defun format-supplied-args-expr (prefix opt-params key-params)
  "Generates Lisp expression constructing a plist of supplied arguments at runtime."
  (cl:let ((parts nil))
    (cl:dolist (pp prefix)
      (cl:let ((lpname (map-param-name (cl:getf pp :name))))
        (cl:push (cl:format nil "(cl:list :~A ~A)" lpname lpname) parts)))
    (cl:dolist (op opt-params)
      (cl:let* ((lpname (map-param-name (cl:getf op :name)))
                (supplied-var (cl:format nil "supplied-~A" lpname)))
        (cl:push (cl:format nil "(cl:when ~A (cl:list :~A ~A))" supplied-var lpname lpname) parts)))
    (cl:dolist (kp key-params)
      (cl:let* ((lpname (map-param-name (cl:getf kp :name)))
             (supplied-var (cl:format nil "supplied-~A" lpname)))
        (cl:push (cl:format nil "(cl:when ~A (cl:list :~A ~A))" supplied-var lpname lpname) parts)))
    (cl:format nil "(cl:append ~{~A~^ ~})" (cl:nreverse parts))))

(cl:defun generate-master-wrapper (stream methods name mname fq-name static-p is-generic-p)
  "Generates Master Wrapper defun with precise dispatch cond block and fallback error signaling."
  (cl:let* ((prefix (common-parameter-prefix methods))
            (prefix-len (cl:length prefix))
            (prefix-names (cl:mapcar (cl:lambda (p) (map-param-name (cl:getf p :name))) prefix))
            (max-mand-len (max-mandatory-parameter-len methods))
            (opt-params (collect-optional-positional-params methods prefix-len max-mand-len))
            (key-params (collect-key-params methods max-mand-len))
            (args-list nil))
    (cl:when is-generic-p
      (cl:setf args-list (cl:append args-list (cl:list "type"))))
    (cl:unless static-p
      (cl:setf args-list (cl:append args-list (cl:list "obj"))))
    (cl:setf args-list (cl:append args-list prefix-names))
    (cl:when opt-params
      (cl:setf args-list (cl:append args-list (cl:list "cl:&optional")))
      (cl:dolist (op opt-params)
        (cl:let* ((op-name (map-param-name (cl:getf op :name)))
                  (supplied-var (cl:format nil "supplied-~A" op-name)))
          (cl:setf args-list (cl:append args-list (cl:list (cl:format nil "(~A cl:nil ~A)" op-name supplied-var)))))))
    (cl:when key-params
      (cl:setf args-list (cl:append args-list (cl:list "cl:&key")))
      (cl:dolist (kp key-params)
        (cl:let* ((kp-name (map-param-name (cl:getf kp :name)))
               (kp-default (find-parameter-default-str (cl:getf kp :name) methods))
               (supplied-var (cl:format nil "supplied-~A" kp-name)))
          (cl:setf args-list (cl:append args-list (cl:list (cl:format nil "(~A ~A ~A)" kp-name kp-default supplied-var)))))))
    
    (cl:format stream "(cl:defun ~A (~{~A~^ ~})~%" mname args-list)
    (cl:format stream "  \"Master wrapper for ~A.~A overloads. Dispatches at runtime.\"~%" fq-name name)
    (cl:format stream "  (cl:cond~%")
    
    ;; Sort methods by parameter count descending for specificity
    (cl:let ((sorted-methods (cl:sort (cl:copy-list methods) #'> :key (cl:lambda (m) (cl:length (cl:getf m :parameters))))))
      (cl:dolist (cm sorted-methods)
        (cl:let ((cond-str (format-master-overload-condition cm prefix opt-params key-params))
              (action-str (format-master-overload-action cm fq-name name static-p is-generic-p prefix opt-params)))
          (cl:format stream "    (~A~%" cond-str)
          (cl:format stream "     ~A)~%" action-str))))
    
    (cl:let ((supplied-args-expr (format-supplied-args-expr prefix opt-params key-params)))
      (cl:format stream "    (cl:t (cl:error 'utils:csharp-overload-not-found~%")
      (cl:format stream "                    :package-name \"~A\"~%" (cl:string-upcase (type-fq-name-to-pkg-name fq-name)))
      (cl:format stream "                    :class-name <type-str>~%")
      (cl:format stream "                    :method-name \"~A\"~%" name)
      (cl:format stream "                    :supplied-args ~A))))~%~%" supplied-args-expr))))

(cl:defun generate-single-overload (stream m mname fq-name static-p)
  "Generates Lisp wrapper function for a single clean C# overload."
  (cl:let* ((m-doc (cl:getf m :documentation))
            (summary (cl:getf m-doc :summary))
            (returns (cl:getf m-doc :returns))
            (params (cl:getf m :parameters))
            (is-generic-p (cl:getf m :is-generic))
            (param-names (cl:mapcar (cl:lambda (p) (map-param-name (cl:getf p :name))) params))
            (args-str (cl:cond
                        ((cl:and static-p is-generic-p)
                         (cl:format nil "type~@[ ~{~A~^ ~}~]" param-names))
                        (static-p
                         (cl:format nil "~{~A~^ ~}" param-names))
                        (is-generic-p
                         (cl:format nil "type obj~@[ ~{~A~^ ~}~]" param-names))
                        (cl:t
                         (cl:format nil "obj~@[ ~{~A~^ ~}~]" param-names))))
            (docstring (build-docstring summary returns params m-doc))
            (escaped-docstring (escape-lisp-string docstring))
            (dotnet-method-name (cl:or (cl:getf m :mangled-name) (cl:getf m :name)))
            ;; For static method params, add (the (dotnet "Type") arg) hints
            (static-typed-args
              (cl:if static-p
                  (cl:mapcar (cl:lambda (pn pt)
                            (cl:format nil "(cl:the (dotnet \"~A\") ~A)" pt pn))
                          param-names
                          (cl:mapcar (cl:lambda (p) (cl:getf p :type)) params))
                  nil)))
       
       (cl:format stream "(cl:defun ~A (~A)~%" mname args-str)
       (cl:when (cl:> (cl:length escaped-docstring) 0)
         (cl:format stream "  \"~A\"~%" escaped-docstring))
       (cl:cond
         ((cl:and static-p is-generic-p)
          (cl:format stream "  (dotnet:static-generic <type-str> \"~A\" (cl:list type)~@[ ~{~A~^ ~}~]))~%~%" dotnet-method-name param-names))
         (static-p
          (cl:if static-typed-args
              (cl:format stream "  (dotnet:static <type-str> \"~A\"~@[~{ ~A~}~]))~%~%" dotnet-method-name static-typed-args)
              (cl:format stream "  (dotnet:static <type-str> \"~A\"~@[ ~{~A~^ ~}~]))~%~%" dotnet-method-name param-names)))
         (is-generic-p
          (cl:format stream "  (dotnet:invoke-generic (cl:the (dotnet \"~A\") obj) \"~A\" (cl:list type)~@[ ~{~A~^ ~}~]))~%~%" fq-name dotnet-method-name param-names))
         (cl:t
          (cl:format stream "  (dotnet:invoke (cl:the (dotnet \"~A\") obj) \"~A\"~@[ ~{~A~^ ~}~]))~%~%" fq-name dotnet-method-name param-names)))))

(defun format-overload-test (cm)
  "Generates a Lisp conditional test expression string for checking if the runtime arguments match the method's parameters."
  (let* ((params (getf cm :parameters))
         (arg-count (length params)))
    (if (= arg-count 0)
        (format nil "(cl:= (cl:length args) 0)")
        (let ((checks (loop for p in params
                            for idx from 0
                            collect (format-param-type-check (getf p :type) (format nil "(cl:nth ~D args)" idx)))))
          (format nil "(cl:and (cl:= (cl:length args) ~D)~{ ~A~})" arg-count checks)))))

(defun generate-class-file (class-plist output-dir &optional constant-properties-list creation-time)
  "Generates the Lisp source file for a single class plist.
   CREATION-TIME, if supplied, is used verbatim as the file's creation-date
   stamp (so a batch of files generated in one run can share a single
   timestamp); otherwise a fresh timestamp is computed."
  (let* ((fq-name (getf class-plist :fully-qualified-name))
         (pkg-name (type-fq-name-to-pkg-name fq-name))
         (output-file (merge-pathnames (make-pathname :name pkg-name :type "lisp")
                                       (pathname (concatenate 'string output-dir "/"))))
         (fields (getf class-plist :fields))
         (properties (getf class-plist :properties))
         (methods (getf class-plist :methods))
         (kind (getf class-plist :kind))
         (raw-ctors (getf class-plist :constructors))
         ;; Structs (value types) in C# have an implicit parameterless constructor.
         ;; If no parameterless constructor is in raw-ctors, we inject one.
         (ctors (if (and (eq kind :struct)
                         (not (some (lambda (ctor) (null (getf ctor :parameters))) raw-ctors)))
                    (cons '(:parameters nil :public t) raw-ctors)
                    raw-ctors))
         (is-value-type-p (or (eq kind :struct) (eq kind :enum)))
         (creation-time (or creation-time (get-iso-8601-time))))
    
    (ensure-directories-exist output-file :verbose t)
    
    ;; 1. Analyze and extract valid Phase 1 members
    (let* ((literal-fields (remove-if-not #'literal-field-p fields))
           (runtime-fields-all (remove-if-not #'runtime-readonly-field-p fields))
           (pure-const-fields (remove-if-not (lambda (f) (or (member "*" constant-properties-list :test #'string=) (member (getf f :name) constant-properties-list :test #'string-equal))) runtime-fields-all))
           (dynamic-const-fields (remove-if (lambda (f) (or (member "*" constant-properties-list :test #'string=) (member (getf f :name) constant-properties-list :test #'string-equal))) runtime-fields-all))
           (const-props (remove-if-not #'constant-property-p properties))
           (pure-const-props (remove-if-not (lambda (p) (or (member "*" constant-properties-list :test #'string=) (member (getf p :name) constant-properties-list :test #'string-equal))) const-props))
           (dynamic-const-props (remove-if (lambda (p) (or (member "*" constant-properties-list :test #'string=) (member (getf p :name) constant-properties-list :test #'string-equal))) const-props))
           (instance-props (remove-if-not #'instance-property-p properties))
           ;; Group methods by name for overload-aware generation
           (non-operator-non-accessor-methods
             (remove-if (lambda (m)
                          (or (uiop:string-prefix-p "op_" (getf m :name))
                              (uiop:string-prefix-p "get_" (getf m :name))
                              (uiop:string-prefix-p "set_" (getf m :name))
                              (generic-type-p (getf m :return-type))
                              (some (lambda (p) (generic-type-p (getf p :type)))
                                    (getf m :parameters))))
                        methods))
           (method-groups
             (let ((table (make-hash-table :test #'equal)))
               (dolist (m non-operator-non-accessor-methods)
                 (push m (gethash (getf m :name) table)))
               (let ((groups nil))
                 (maphash (lambda (name methods)
                            (push (cons name (nreverse methods)) groups))
                           table)
                 (nreverse groups))))
           (clean-ctors (remove-if-not #'clean-constructor-p ctors))
           (dirty-ctors (remove-if-not #'dirty-constructor-p ctors))
           (clean-ctor-count (length clean-ctors))
           (dirty-ctor-count (length dirty-ctors))
           (exports nil)
           (shadows nil))
      
      ;; Collect all exports
      (push "<type>" exports)
      (push "<type-str>" exports)
      (push "<creation>" exports)
      (push "<version>" exports)
      
      ;; Collect constructor exports
      (when (> clean-ctor-count 0)
        (push "new" exports)
        (when (>= clean-ctor-count 2)
          (dolist (c clean-ctors)
            (let ((params (getf c :parameters)))
              (when params
                (push (constructor-overload-name c) exports))))))
      
      (dolist (f literal-fields)
        (push (format nil "+~A+" (camel-to-kebab (getf f :name))) exports))
      (dolist (f pure-const-fields)
        (push (format nil "+~A+" (camel-to-kebab (getf f :name))) exports))
      (dolist (f dynamic-const-fields)
        (push (map-member-name (getf f :name)) exports))
      (dolist (p pure-const-props)
        (push (format nil "+~A+" (camel-to-kebab (getf p :name))) exports))
      (dolist (p dynamic-const-props)
        (push (map-member-name (getf p :name)) exports))
      (dolist (p instance-props)
        (let* ((pname (map-member-name (getf p :name)))
               (readable (getf p :readable)))
          (if readable
              (push pname exports)
              (push (format nil "set-~A" pname) exports))))
      ;; Collect method exports from method groups
      (dolist (group method-groups)
        (let* ((name (car group))
               (clean-methods (remove-if-not #'clean-method-p (cdr group)))
               (clean-count (length clean-methods))
               (kebab-name (map-member-name name))
               (static-clean (remove-if-not (lambda (m) (getf m :is-static)) clean-methods))
               (instance-clean (remove-if-not (lambda (m) (not (getf m :is-static))) clean-methods))
               (static-count (length static-clean))
               (instance-count (length instance-clean))
               (mixed-mode-p (and (> static-count 0) (> instance-count 0))))
          (when (> clean-count 0)
            (push kebab-name exports)
            (when mixed-mode-p
              (push (concatenate 'string kebab-name "*") exports)))
          (when (>= clean-count 2)
            ;; Export type-suffixed names for multi-overload methods
            (dolist (cm clean-methods)
              (push (method-overload-name cm) exports)))))
      
      ;; Remove duplicates from exports while preserving order
      (setf exports (remove-duplicates (nreverse exports) :test #'string= :from-end t))
      
      ;; Identify exported symbols that conflict with CL and must be shadowed
      (dolist (exp exports)
        (multiple-value-bind (sym status) (find-symbol (string-upcase exp) :common-lisp)
          (when (and sym (eq status :external))
            (push exp shadows))))
      ;; Remove duplicates from shadows while preserving order
      (setf shadows (remove-duplicates (nreverse shadows) :test #'string= :from-end t))
      
      ;; 2. Write to the Lisp output file
      (with-open-file (stream output-file :direction :output :if-exists :supersede :if-does-not-exist :create)
        ;; Comments
        (format stream ";;; Generated automatically. Do not edit.~%")
        (format stream ";;; Class: ~A~%" fq-name)
        (format stream ";;; Generator Version: ~D~%" *generator-version*)
        (format stream ";;; Creation Date: ~A~%~%" creation-time)
        
        ;; Preamble
        (format stream "(cl:in-package :cl-user)~%~%")
        (format stream "(cl:defpackage :~A~%" pkg-name)
        (format stream "  (:use :cl)~%")
        (when shadows
          (format stream "  (:shadow~%")
          (dolist (shad shadows)
            (format stream "   #:~A~%" shad))
          (format stream "  )~%"))
        (format stream "  (:export~%")
        (dolist (exp exports)
          (format stream "   #:~A~%" exp))
        (format stream "  ))~%~%")
        
        (format stream "(cl:in-package :~A)~%~%" pkg-name)
        
        ;; Type Constants
        (format stream "(cl:defconstant <type> (monoutils:get-type \"~A\"))~%" fq-name)
        (format stream "(cl:defconstant <type-str> \"~A\")~%" fq-name)
        (format stream "(cl:defconstant <creation> \"~A\")~%" creation-time)
        (format stream "(cl:defconstant <version> ~D)~%~%" *generator-version*)
        
        ;; CLOS Type Registration
        (format stream ";; Register C# Type with CLOS~%")
        (format stream "(cl:eval-when (:compile-toplevel :load-toplevel :execute)~%")
        (format stream "  (dotnet:static \"DotCL.Runtime\" \"EnsureDotNetTypeClass\"~%")
        (format stream "                 (dotnet:resolve-type \"~A\")))~%~%" fq-name)
        
        ;; Constructors
        (cond
          ;; Case 1: No clean constructors - all are dirty
          ((and (> dirty-ctor-count 0) (= clean-ctor-count 0))
           (format stream ";; The following C# ~A constructors have special parameter types~%" fq-name)
           (format stream ";; (ref, out, params, or defaults) and are not yet supported:~%")
           (dolist (dc dirty-ctors)
             (format stream ";;   ~A~%" (constructor-signature-str dc)))
           (format stream "~%"))
          
          ;; Case 2: Single clean constructor
          ((= clean-ctor-count 1)
           (let* ((c (first clean-ctors))
                  (c-doc (getf c :documentation))
                  (summary (getf c-doc :summary))
                  (returns (getf c-doc :returns))
                  (params (getf c :parameters))
                  (param-names (mapcar (lambda (p) (map-param-name (getf p :name))) params))
                  (args-str (format nil "~{~A~^ ~}" param-names))
                  (docstring (build-docstring summary returns params c-doc))
                  (escaped-docstring (escape-lisp-string docstring)))
             (format stream "(cl:defun new (~A)~%" args-str)
             (when (> (length escaped-docstring) 0)
               (format stream "  \"~A\"~%" escaped-docstring))
             (format stream "  (dotnet:new <type-str>~@[ ~{~A~^ ~}~]))~%~%" param-names)
             ;; Emit dirty constructor doc-comments if any
             (when (> dirty-ctor-count 0)
               (format stream ";; Note: ~A also has the following constructors with special~%" fq-name)
               (format stream ";; parameter types (ref, out, params, or defaults) that are not~%")
               (format stream ";; yet supported:~%")
               (dolist (dc dirty-ctors)
                 (format stream ";;   ~A~%" (constructor-signature-str dc)))
               (format stream "~%"))))
          
          ;; Case 3: Multiple clean constructors
          ((>= clean-ctor-count 2)
           ;; Generate passthrough &rest function for DotCL runtime dispatch
           (format stream "(cl:defun new (cl:&rest args)~%")
           (format stream "  \"Passthrough constructor for ~A. Dispatches at runtime.\"~%" fq-name)
           (format stream "  (cl:apply (cl:function dotnet:new) <type-str> args))~%~%")
           ;; Generate per-overload typed functions with type-suffixed names
           (dolist (c clean-ctors)
             (let ((params (getf c :parameters)))
               (when params
                 (let* ((cname (constructor-overload-name c))
                        (c-doc (getf c :documentation))
                        (summary (getf c-doc :summary))
                        (returns (getf c-doc :returns))
                        (param-names (mapcar (lambda (p) (map-param-name (getf p :name))) params))
                        (overload-signature (constructor-signature-str c))
                        (args-str (format nil "~{~A~^ ~}" param-names))
                        (docstring (build-docstring summary returns params c-doc))
                        (overload-note (format nil "Calls ~A constructor ~A" fq-name overload-signature))
                        (full-docstring (if (> (length docstring) 0)
                                            (concatenate 'string overload-note ". " docstring)
                                            overload-note))
                        (escaped-full-doc (escape-lisp-string full-docstring)))
                   (format stream "(cl:defun ~A (~A)~%" cname args-str)
                   (format stream "  \"~A\"~%" escaped-full-doc)
                   (format stream "  (dotnet:new <type-str>~@[ ~{~A~^ ~}~]))~%~%" param-names)))))
           ;; Emit dirty constructor doc-comments if any
           (when (> dirty-ctor-count 0)
             (format stream ";; Note: ~A also has the following constructors with special~%" fq-name)
             (format stream ";; parameter types (ref, out, params, or defaults) that are not~%")
             (format stream ";; yet supported:~%")
             (dolist (dc dirty-ctors)
               (format stream ";;   ~A~%" (constructor-signature-str dc)))
             (format stream "~%"))))
        
        ;; Compile-Time Constants (Literal Fields)
        (dolist (f literal-fields)
          (let* ((cname (format nil "+~A+" (camel-to-kebab (getf f :name))))
                 (f-doc (getf (getf f :documentation) :summary))
                 (doc-str (if f-doc (escape-lisp-string f-doc) "")))
            (format stream "(cl:defconstant ~A (dotnet:static <type-str> \"~A\"))~%" cname (getf f :name))
            (if (> (length doc-str) 0)
                (format stream "(cl:setf (cl:documentation (cl:quote ~A) (cl:quote cl:variable)) \"~A\")~%~%" cname doc-str)
                (format stream "~%"))))
        
        ;; Runtime Read-Only Fields (Constants)
        (dolist (f pure-const-fields)
          (let* ((cname (format nil "+~A+" (camel-to-kebab (getf f :name))))
                 (f-doc (getf (getf f :documentation) :summary))
                 (doc-str (if f-doc (escape-lisp-string f-doc) "")))
            (format stream "(cl:defconstant ~A (dotnet:static <type-str> \"~A\"))~%" cname (getf f :name))
            (if (> (length doc-str) 0)
                (format stream "(cl:setf (cl:documentation (cl:quote ~A) (cl:quote cl:variable)) \"~A\")~%~%" cname doc-str)
                (format stream "~%"))))

        ;; Runtime Read-Only Fields (Dynamic)
        (dolist (f dynamic-const-fields)
          (let* ((cname (map-member-name (getf f :name)))
                 (f-doc (getf (getf f :documentation) :summary))
                 (doc-str (if f-doc (escape-lisp-string f-doc) "")))
            (format stream "(cl:define-symbol-macro ~A (dotnet:static <type-str> \"~A\"))~%" cname (getf f :name))
            (if (> (length doc-str) 0)
                (format stream "(cl:setf (cl:documentation (cl:quote ~A) (cl:quote cl:variable)) \"~A\")~%~%" cname doc-str)
                (format stream "~%"))))
        
        ;; Runtime Read-Only Properties
        ;; Pure Constant Properties
        (dolist (p pure-const-props)
          (let* ((cname (format nil "+~A+" (camel-to-kebab (getf p :name))))
                 (p-doc (getf (getf p :documentation) :summary))
                 (doc-str (if p-doc (escape-lisp-string p-doc) "")))
            (format stream "(cl:defconstant ~A (dotnet:static <type-str> \"~A\"))~%" cname (getf p :name))
            (if (> (length doc-str) 0)
                (format stream "(cl:setf (cl:documentation (cl:quote ~A) (cl:quote cl:variable)) \"~A\")~%~%" cname doc-str)
                (format stream "~%"))))

        ;; Runtime Read-Only Properties
        (dolist (p dynamic-const-props)
          (let* ((cname (map-member-name (getf p :name)))
                 (p-doc (getf (getf p :documentation) :summary))
                 (doc-str (if p-doc (escape-lisp-string p-doc) "")))
            (format stream "(cl:define-symbol-macro ~A (dotnet:static <type-str> \"~A\"))~%" cname (getf p :name))
            (if (> (length doc-str) 0)
                (format stream "(cl:setf (cl:documentation (cl:quote ~A) (cl:quote cl:variable)) \"~A\")~%~%" cname doc-str)
                (format stream "~%"))))
        
        ;; Instance Properties
        (dolist (p instance-props)
          (let* ((pname (map-member-name (getf p :name)))
                 (readable (getf p :readable))
                 (writeable (getf p :writeable))
                 (get-method (getf p :get-method))
                 (set-method (getf p :set-method))
                 (p-doc (getf (getf p :documentation) :summary))
                 (doc-str (if p-doc (escape-lisp-string p-doc) "")))
            (when readable
              (format stream "(cl:defun ~A (obj)~%" pname)
              (when (> (length doc-str) 0)
                (format stream "  \"~A\"~%" doc-str))
              (format stream "  (dotnet:invoke (cl:the (dotnet \"~A\") obj) \"~A\"))~%~%" fq-name get-method))
            (when writeable
              (if readable
                  (progn
                    (when is-value-type-p
                      (format stream ";; Note: Modifying a property of a value type (struct) via setf may only mutate~%")
                      (format stream ";; a boxed copy, leaving the original unchanged. Use caution with structs.~%"))
                    (format stream "(cl:defun (cl:setf ~A) (new-value obj)~%" pname)
                    (when (> (length doc-str) 0)
                      (format stream "  \"~A\"~%" doc-str))
                    (format stream "  (dotnet:invoke (cl:the (dotnet \"~A\") obj) \"~A\" new-value))~%~%" fq-name set-method))
                  (progn
                    (when is-value-type-p
                      (format stream ";; Note: Modifying a property of a value type (struct) via setf may only mutate~%")
                      (format stream ";; a boxed copy, leaving the original unchanged. Use caution with structs.~%"))
                    (format stream "(cl:defun set-~A (obj new-value)~%" pname)
                    (when (> (length doc-str) 0)
                      (format stream "  \"~A\"~%" doc-str))
                    (format stream "  (dotnet:invoke (cl:the (dotnet \"~A\") obj) \"~A\" new-value))~%~%" fq-name set-method))))))
        
        ;; Methods - Generated from method groups with overload handling
        (dolist (group method-groups)
          (let* ((name (car group))
                 (group-methods (cdr group))
                 (clean-methods (remove-if-not #'clean-method-p group-methods))
                 (dirty-methods (remove-if-not #'dirty-method-p group-methods))
                 (clean-count (length clean-methods))
                 (dirty-count (length dirty-methods))
                 (kebab-name (map-member-name name))
                 (static-clean (remove-if-not (lambda (m) (getf m :is-static)) clean-methods))
                 (instance-clean (remove-if-not (lambda (m) (not (getf m :is-static))) clean-methods))
                 (static-count (length static-clean))
                 (instance-count (length instance-clean))
                 (mixed-mode-p (and (> static-count 0) (> instance-count 0))))
            
            (cond
              ;; Case 1: No clean overloads - all are dirty (ref/out/params/defaults)
              ((= clean-count 0)
               (format stream ";; The following C# ~A.~A overloads have special parameter types~%" fq-name name)
               (format stream ";; (ref, out, params, or defaults) and are not yet supported:~%")
               (dolist (dm dirty-methods)
                 (format stream ";;   ~A~%" (method-signature-str dm)))
               (format stream "~%"))
              
               ;; Case 2: Clean overloads exist
              (t
               (cl:cond
                 (mixed-mode-p
                  ;; Mixed-Mode: instance name is kebab-name, static name is kebab-name*
                  (cl:let ((static-kebab-name (concatenate 'string kebab-name "*")))
                    ;; Instance wrappers
                    (cl:if (cl:and (= instance-count 1) (cl:not (complex-group-p instance-clean)))
                           (generate-single-overload stream (first instance-clean) kebab-name fq-name nil)
                           (generate-master-wrapper stream instance-clean name kebab-name fq-name nil (getf (first instance-clean) :is-generic)))
                    ;; Static wrappers
                    (cl:if (cl:and (= static-count 1) (cl:not (complex-group-p static-clean)))
                           (generate-single-overload stream (first static-clean) static-kebab-name fq-name t)
                           (generate-master-wrapper stream static-clean name static-kebab-name fq-name t (getf (first static-clean) :is-generic)))))
                 (t
                  ;; Single-Mode: name is kebab-name
                  (cl:cond
                    ((> static-count 0)
                     (cl:if (cl:and (= static-count 1) (cl:not (complex-group-p static-clean)))
                            (generate-single-overload stream (first static-clean) kebab-name fq-name t)
                            (generate-master-wrapper stream static-clean name kebab-name fq-name t (getf (first static-clean) :is-generic))))
                    ((> instance-count 0)
                     (cl:if (cl:and (= instance-count 1) (cl:not (complex-group-p instance-clean)))
                            (generate-single-overload stream (first instance-clean) kebab-name fq-name nil)
                            (generate-master-wrapper stream instance-clean name kebab-name fq-name nil (getf (first instance-clean) :is-generic)))))))
               
               ;; Generate per-overload typed functions with type-suffixed names (for clean-count >= 2)
               (when (>= clean-count 2)
                 (dolist (cm clean-methods)
                   (let* ((mname (method-overload-name cm))
                          (m-doc (getf cm :documentation))
                          (summary (getf m-doc :summary))
                          (returns (getf m-doc :returns))
                          (params (getf cm :parameters))
                          (is-generic-overload-p (getf cm :is-generic))
                          (is-static-overload-p (getf cm :is-static))
                          (param-names (mapcar (lambda (p) (map-param-name (getf p :name))) params))
                          (overload-signature (method-signature-str cm))
                          (args-str (cl:cond
                                      ((and is-static-overload-p is-generic-overload-p)
                                       (format nil "type~@[ ~{~A~^ ~}~]" param-names))
                                      (is-static-overload-p
                                       (format nil "~{~A~^ ~}" param-names))
                                      (is-generic-overload-p
                                       (format nil "type obj~@[ ~{~A~^ ~}~]" param-names))
                                      (cl:t
                                       (format nil "obj~@[ ~{~A~^ ~}~]" param-names))))
                          (docstring (build-docstring summary returns params m-doc))
                          (escaped-docstring (escape-lisp-string docstring))
                          ;; Construct a note about the specific overload signature
                          (overload-note (format nil "Calls ~A.~A ~A" fq-name name overload-signature))
                          (full-docstring (if (> (length docstring) 0)
                                              (concatenate 'string overload-note ". " docstring)
                                              overload-note))
                          (escaped-full-doc (escape-lisp-string full-docstring))
                          (dotnet-method-name (or (getf cm :mangled-name) name))
                          ;; Static method type hints for typed overloads
                          (static-typed-args
                            (if is-static-overload-p
                                (mapcar (lambda (pn pt)
                                          (format nil "(cl:the (dotnet \"~A\") ~A)" pt pn))
                                        param-names
                                        (mapcar (lambda (p) (getf p :type)) params))
                                nil)))
                     (format stream "(cl:defun ~A (~A)~%" mname args-str)
                     (format stream "  \"~A\"~%" escaped-full-doc)
                     (cl:cond
                       ((and is-static-overload-p is-generic-overload-p)
                        (format stream "  (dotnet:static-generic <type-str> \"~A\" (cl:list type)~@[ ~{~A~^ ~}~]))~%~%" dotnet-method-name param-names))
                       (is-static-overload-p
                        (if static-typed-args
                            (format stream "  (dotnet:static <type-str> \"~A\"~@[~{ ~A~}~]))~%~%" dotnet-method-name static-typed-args)
                            (format stream "  (dotnet:static <type-str> \"~A\"~@[ ~{~A~^ ~}~]))~%~%" dotnet-method-name param-names)))
                       (is-generic-overload-p
                        (format stream "  (dotnet:invoke-generic (cl:the (dotnet \"~A\") obj) \"~A\" (cl:list type)~@[ ~{~A~^ ~}~]))~%~%" fq-name dotnet-method-name param-names))
                       (cl:t
                        (format stream "  (dotnet:invoke (cl:the (dotnet \"~A\") obj) \"~A\"~@[ ~{~A~^ ~}~]))~%~%" fq-name dotnet-method-name param-names))))))
               
               ;; Emit dirty overload doc-comment if any
               (when (> dirty-count 0)
                 (format stream ";; Note: ~A.~A also has the following overloads with special~%" fq-name name)
                 (format stream ";; parameter types (ref, out, params, or defaults) that are not~%")
                 (format stream ";; yet supported:~%")
                 (dolist (dm dirty-methods)
                   (format stream ";;   ~A~%" (method-signature-str dm)))
                 (format stream "~%"))))))
        ) ;; close with-open-file
      ) ;; close inner analysis let*
    ) ;; close outer let*
  ) ;; close defun generate-class-file

(defun resolve-batch-entry (entry)
  "Loads ENTRY's :metadata-file and resolves each of its :classes by
   :fully-qualified-name against the loaded metadata. Returns two values:
   a list of (class-plist . constant-properties-list) pairs ready for
   generate-class-file, and a list of class names from :classes that could
   not be found in the metadata (empty if all resolved, or if :classes was
   empty, which is a valid metadata-only request)."
  (let* ((metadata-file (getf entry :metadata-file))
         (classes (getf entry :classes)))
    (unless (probe-file metadata-file)
      (error "Metadata file not found: ~A" metadata-file))
    (let ((metadata (utils:safe-read-form-from-file metadata-file))
          (resolved nil)
          (not-found nil))
      (dolist (class-entry classes)
        (let* ((cname (getf class-entry :name))
               (cprops-str (getf class-entry :constant-properties))
               (cprops (and cprops-str (> (length cprops-str) 0) (split-string cprops-str #\,)))
               (cls (find cname metadata :key (lambda (c) (getf c :fully-qualified-name)) :test #'string=)))
          (if cls
              (push (cons cls cprops) resolved)
              (push cname not-found))))
      (values (nreverse resolved) (nreverse not-found)))))

(defun generate-assembly-packages-batch (assembly-entries output-dir creation-time)
  "Loads each entry's metadata file, resolves all requested classes across
   all entries, and only then generates the .lisp package files, so a
   class name that cannot be found aborts the whole run before anything is
   written. An entry with an empty :classes list is not an error -- it
   means only that entry's metadata file (already written by C#) was
   requested."
  (let ((all-resolved nil)
        (all-not-found nil))
    (dolist (entry assembly-entries)
      (multiple-value-bind (resolved not-found) (resolve-batch-entry entry)
        (setf all-resolved (append all-resolved resolved))
        (setf all-not-found (append all-not-found not-found))))

    (when all-not-found
      (dolist (cname all-not-found)
        (utils:format-red *error-output* "Error: Class not found in assembly metadata: ~A~%" cname))
      (error "One or more requested classes were not found: ~{~A~^, ~}" all-not-found))

    (dolist (pair all-resolved)
      (let ((cls (car pair))
            (cprops (cdr pair)))
        (format *error-output* "Generating package for C# Class: ~A~%" (getf cls :fully-qualified-name))
        (generate-class-file cls output-dir cprops creation-time)))

    t))

(defun run-assembly-package-generator-batch (manifest-file output-dir creation-time)
  "CLI entry point called by DotclHost.Call for the single-pass generator.
   MANIFEST-FILE is a Lisp-reader-compatible list of plists, one per
   assembly:
     ((:metadata-file \"...\" :classes ((:name \"...\" :constant-properties \"...\") ...)) ...)
   Maps string parameters safely and reports errors in red."
  (handler-case
      (let ((mfile (and manifest-file (> (length manifest-file) 0) manifest-file))
            (odir (and output-dir (> (length output-dir) 0) output-dir)))
        (unless mfile
          (error "Manifest file path is required."))
        (unless odir
          (error "Output directory path is required."))
        (unless (probe-file mfile)
          (error "Manifest file not found: ~A" mfile))
        (let ((assembly-entries (utils:safe-read-form-from-file mfile)))
          (generate-assembly-packages-batch assembly-entries odir creation-time)))
    (error (c)
      (utils:format-red *error-output* "Error in assembly-package-generator: ~A~%" c)
      (error c))))
