;;; Generated automatically. Do not edit.
;;; Generator Version: 31
;;; Creation Date: 2026-07-04T16:50:34Z

(asdf:defsystem "csharp-assembly-packages"
  :author "DotCL C# Assembly Package Generator"
  :version "31"
  :homepage "https://github.com/LispEngineer/dotcl-package-generator"
  :description "Lisp packages enabling ease-of-interoperation with selected C# classes and objects."
  :long-description "Generated by dotcl-packagegen 2.30.0 (package format version 31)
Generation date: 2026-07-04T16:50:34Z

Packages included:
  System.Console.dll
    System.Console => system-console
  System.Runtime.dll
    System.TimeSpan => system-time-span
      Constant properties: *
    System.Object => system-object
    System.Type => system-type
    System.String => system-string
    System.Array => system-array
      Constant properties: MaxLength
    System.TimeZoneInfo => system-time-zone-info
    System.Convert => system-convert
    System.Text.StringBuilder => system-text-string-builder
    System.TimeZoneInfo+AdjustmentRule => system-time-zone-info-adjustment-rule
    System.ValueTuple`2 => system-value-tuple-2
    System.ValueTuple`3 => system-value-tuple-3
    System.ValueTuple`4 => system-value-tuple-4
    System.ValueTuple`5 => system-value-tuple-5
    System.ValueTuple`6 => system-value-tuple-6
    System.ValueTuple`7 => system-value-tuple-7
    System.ValueTuple`8 => system-value-tuple-8
  System.Linq.dll
    System.Linq.Enumerable => system-linq-enumerable
  System.Xml.ReaderWriter.dll
    System.Xml.XmlReader => system-xml-xml-reader
  System.Collections.dll
    System.Collections.Generic.Dictionary`2 => system-collections-generic-dictionary-2
    System.Collections.Generic.Dictionary`2+KeyCollection => system-collections-generic-dictionary-2-key-collection
    System.Collections.Generic.Dictionary`2+ValueCollection => system-collections-generic-dictionary-2-value-collection
    System.Collections.Generic.List`1 => system-collections-generic-list-1
    System.Collections.Generic.SortedList`2 => system-collections-generic-sorted-list-2
  System.Numerics.Vectors.dll
    System.Numerics.Vector2 => system-numerics-vector2
      Constant properties: *
    System.Numerics.Vector3 => system-numerics-vector3
      Constant properties: *
    System.Numerics.Vector4 => system-numerics-vector4
      Constant properties: *
  System.Diagnostics.Debug.dll
    System.Diagnostics.Debug => system-diagnostics-debug
  System.Globalization.dll
    System.Globalization.CultureInfo => system-globalization-culture-info
  System.Net.ServicePoint.dll
    System.Net.ServicePointManager => system-net-service-point-manager
  System.Runtime.Extensions.dll
    System.Environment => system-environment
    System.AppDomain => system-app-domain
  System.Threading.Thread.dll
    System.Threading.Thread => system-threading-thread
"
  :components (
   (:file "packages")
   (:file "csharp-assembly-utils" :depends-on ("packages"))
   (:file "system-console" :depends-on ("packages" "csharp-assembly-utils"))
   (:file "system-time-span" :depends-on ("packages" "csharp-assembly-utils"))
   (:file "system-object" :depends-on ("packages" "csharp-assembly-utils"))
   (:file "system-type" :depends-on ("packages" "csharp-assembly-utils"))
   (:file "system-string" :depends-on ("packages" "csharp-assembly-utils"))
   (:file "system-array" :depends-on ("packages" "csharp-assembly-utils"))
   (:file "system-time-zone-info" :depends-on ("packages" "csharp-assembly-utils"))
   (:file "system-convert" :depends-on ("packages" "csharp-assembly-utils"))
   (:file "system-text-string-builder" :depends-on ("packages" "csharp-assembly-utils"))
   (:file "system-time-zone-info-adjustment-rule" :depends-on ("packages" "csharp-assembly-utils"))
   (:file "system-value-tuple-2" :depends-on ("packages" "csharp-assembly-utils"))
   (:file "system-value-tuple-3" :depends-on ("packages" "csharp-assembly-utils"))
   (:file "system-value-tuple-4" :depends-on ("packages" "csharp-assembly-utils"))
   (:file "system-value-tuple-5" :depends-on ("packages" "csharp-assembly-utils"))
   (:file "system-value-tuple-6" :depends-on ("packages" "csharp-assembly-utils"))
   (:file "system-value-tuple-7" :depends-on ("packages" "csharp-assembly-utils"))
   (:file "system-value-tuple-8" :depends-on ("packages" "csharp-assembly-utils"))
   (:file "system-linq-enumerable" :depends-on ("packages" "csharp-assembly-utils"))
   (:file "system-xml-xml-reader" :depends-on ("packages" "csharp-assembly-utils"))
   (:file "system-collections-generic-dictionary-2" :depends-on ("packages" "csharp-assembly-utils"))
   (:file "system-collections-generic-dictionary-2-key-collection" :depends-on ("packages" "csharp-assembly-utils"))
   (:file "system-collections-generic-dictionary-2-value-collection" :depends-on ("packages" "csharp-assembly-utils"))
   (:file "system-collections-generic-list-1" :depends-on ("packages" "csharp-assembly-utils"))
   (:file "system-collections-generic-sorted-list-2" :depends-on ("packages" "csharp-assembly-utils"))
   (:file "system-numerics-vector2" :depends-on ("packages" "csharp-assembly-utils"))
   (:file "system-numerics-vector3" :depends-on ("packages" "csharp-assembly-utils"))
   (:file "system-numerics-vector4" :depends-on ("packages" "csharp-assembly-utils"))
   (:file "system-diagnostics-debug" :depends-on ("packages" "csharp-assembly-utils"))
   (:file "system-globalization-culture-info" :depends-on ("packages" "csharp-assembly-utils"))
   (:file "system-net-service-point-manager" :depends-on ("packages" "csharp-assembly-utils"))
   (:file "system-environment" :depends-on ("packages" "csharp-assembly-utils"))
   (:file "system-app-domain" :depends-on ("packages" "csharp-assembly-utils"))
   (:file "system-threading-thread" :depends-on ("packages" "csharp-assembly-utils"))
  ))
