;;; Generated automatically. Do not edit.
;;; Generator Version: 22
;;; Creation Date: 2026-07-03T12:54:32Z

(asdf:defsystem "csharp-assembly-packages"
  :author "DotCL C# Assembly Package Generator"
  :version "22"
  :homepage "https://github.com/LispEngineer/dotcl-package-generator"
  :description "Lisp packages enabling ease-of-interoperation with selected C# classes and objects."
  :long-description "Generated by dotcl-packagegen 2.22.0 (package format version 22)
Generation date: 2026-07-03T12:54:32Z

Packages included:
  System.Runtime.dll
    System.TimeSpan => system-time-span
      Constant properties: *
    System.Object => system-object
    System.Type => system-type
    System.String => system-string
    System.TimeZoneInfo => system-time-zone-info
    System.TimeZoneInfo+AdjustmentRule => system-time-zone-info-adjustment-rule
  System.Linq.dll
    System.Linq.Enumerable => system-linq-enumerable
  System.Xml.ReaderWriter.dll
    System.Xml.XmlReader => system-xml-xml-reader
  System.Collections.dll
    System.Collections.Generic.Dictionary`2 => system-collections-generic-dictionary-2
    System.Collections.Generic.Dictionary`2+KeyCollection => system-collections-generic-dictionary-2-key-collection
    System.Collections.Generic.Dictionary`2+ValueCollection => system-collections-generic-dictionary-2-value-collection
"
  :components (
   (:file "packages")
   (:file "system-time-span" :depends-on ("packages"))
   (:file "system-object" :depends-on ("packages"))
   (:file "system-type" :depends-on ("packages"))
   (:file "system-string" :depends-on ("packages"))
   (:file "system-time-zone-info" :depends-on ("packages"))
   (:file "system-time-zone-info-adjustment-rule" :depends-on ("packages"))
   (:file "system-linq-enumerable" :depends-on ("packages"))
   (:file "system-xml-xml-reader" :depends-on ("packages"))
   (:file "system-collections-generic-dictionary-2" :depends-on ("packages"))
   (:file "system-collections-generic-dictionary-2-key-collection" :depends-on ("packages"))
   (:file "system-collections-generic-dictionary-2-value-collection" :depends-on ("packages"))
  ))
