;;; Generated automatically. Do not edit.
;;; Generator Version: 53
;;; Creation Date: 2026-07-19T16:02:09Z

(asdf:defsystem "csharp-assembly-packages"
  :author "DotCL C# Assembly Package Generator"
  :version "53"
  :homepage "https://github.com/LispEngineer/dotcl-package-generator"
  :description "Lisp packages enabling ease-of-interoperation with selected C# classes and objects."
  :long-description "Generated by dotcl-packagegen 2.53.0 (package format version 53)
Generation date: 2026-07-19T16:02:09Z
Global flags: --skip-missing --no-csharp-generic-in-asd

Packages included:
  System.Console.dll
    System.Console => system-console
      Options: (none)
  System.Runtime.dll
    System.TimeSpan => system-time-span
      Constant properties: *
      Options: (none)
    System.Object => system-object
      Options: --defgeneric
    System.Type => system-type
      Options: (none)
    System.String => system-string
      Options: --defgeneric
    System.Array => system-array
      Constant properties: MaxLength
      Options: --defgeneric
    System.TimeZoneInfo => system-time-zone-info
      Options: (none)
    System.Convert => system-convert
      Options: (none)
    System.Text.StringBuilder => system-text-string-builder
      Options: --defgeneric
    System.TimeZoneInfo+AdjustmentRule => system-time-zone-info-adjustment-rule
      Options: (none)
    System.ValueTuple`2 => system-value-tuple-2
      Options: --export-interfaces
    System.ValueTuple`3 => system-value-tuple-3
      Options: (none)
    System.ValueTuple`4 => system-value-tuple-4
      Options: (none)
    System.ValueTuple`5 => system-value-tuple-5
      Options: (none)
    System.ValueTuple`6 => system-value-tuple-6
      Options: (none)
    System.ValueTuple`7 => system-value-tuple-7
      Options: (none)
    System.ValueTuple`8 => system-value-tuple-8
      Options: (none)
    System.ArgumentOutOfRangeException => system-argument-out-of-range-exception
      Options: --export-interfaces --export-object --export-parents
    System.Collections.Hashtable => system-collections-hashtable
      Options: (none)
    System.IO.MemoryStream => system-io-memory-stream
      Options: --export-interfaces --export-object --export-parents
    System.IO.StreamReader => system-io-stream-reader
      Options: --export-interfaces --export-parents
    System.Collections.IStructuralComparable => system-collections-i-structural-comparable
      Options: --export-interfaces
      Discovered via: --export-interfaces from System.ValueTuple`2
    System.Collections.IStructuralEquatable => system-collections-i-structural-equatable
      Options: --export-interfaces
      Discovered via: --export-interfaces from System.ValueTuple`2
    System.IComparable => system-i-comparable
      Options: --export-interfaces
      Discovered via: --export-interfaces from System.ValueTuple`2
    System.IComparable`1 => system-i-comparable-1
      Options: --export-interfaces
      Discovered via: --export-interfaces from System.ValueTuple`2
    System.IEquatable`1 => system-i-equatable-1
      Options: --export-interfaces
      Discovered via: --export-interfaces from System.ValueTuple`2
    System.Runtime.CompilerServices.ITuple => system-runtime-compiler-services-i-tuple
      Options: --export-interfaces
      Discovered via: --export-interfaces from System.ValueTuple`2
    System.ArgumentException => system-argument-exception
      Options: --export-interfaces --export-object --export-parents
      Discovered via: --export-parents/--export-interfaces from System.ArgumentOutOfRangeException
    System.Runtime.Serialization.ISerializable => system-runtime-serialization-i-serializable
      Options: --export-interfaces --export-object --export-parents
      Discovered via: --export-parents/--export-interfaces from System.ArgumentOutOfRangeException
    System.SystemException => system-system-exception
      Options: --export-interfaces --export-object --export-parents
      Discovered via: --export-parents/--export-interfaces from System.ArgumentOutOfRangeException
    System.Exception => system-exception
      Options: --export-interfaces --export-object --export-parents
      Discovered via: --export-parents/--export-interfaces from System.ArgumentOutOfRangeException
    System.IO.Stream => system-io-stream
      Options: --export-interfaces --export-object --export-parents
      Discovered via: --export-parents/--export-interfaces from System.IO.MemoryStream
    System.IAsyncDisposable => system-i-async-disposable
      Options: --export-interfaces --export-object --export-parents
      Discovered via: --export-parents/--export-interfaces from System.IO.MemoryStream
    System.IDisposable => system-i-disposable
      Options: --export-interfaces --export-object --export-parents
      Discovered via: --export-parents/--export-interfaces from System.IO.MemoryStream
    System.MarshalByRefObject => system-marshal-by-ref-object
      Options: --export-interfaces --export-object --export-parents
      Discovered via: --export-parents/--export-interfaces from System.IO.MemoryStream
    System.IO.TextReader => system-io-text-reader
      Options: --export-interfaces --export-parents
      Discovered via: --export-parents/--export-interfaces from System.IO.StreamReader
    System.Collections.ICollection => system-collections-i-collection
      Options: --export-interfaces --export-object --export-parents
      Discovered via: --export-parents/--export-interfaces from System.Collections.Specialized.NameValueCollection
    System.Collections.IEnumerable => system-collections-i-enumerable
      Options: --export-interfaces --export-object --export-parents
      Discovered via: --export-parents/--export-interfaces from System.Collections.Specialized.NameValueCollection
    System.Runtime.Serialization.IDeserializationCallback => system-runtime-serialization-i-deserialization-callback
      Options: --export-interfaces --export-object --export-parents
      Discovered via: --export-parents/--export-interfaces from System.Collections.Specialized.NameValueCollection
  System.Linq.dll
    System.Linq.Enumerable => system-linq-enumerable
      Options: --export-parents
  System.Xml.ReaderWriter.dll
    System.Xml.XmlReader => system-xml-xml-reader
      Options: --export-interfaces
  System.Collections.dll
    System.Collections.Generic.Dictionary`2 => system-collections-generic-dictionary-2
      Options: --defgeneric
    System.Collections.Generic.Dictionary`2+KeyCollection => system-collections-generic-dictionary-2-key-collection
      Options: (none)
    System.Collections.Generic.Dictionary`2+ValueCollection => system-collections-generic-dictionary-2-value-collection
      Options: (none)
    System.Collections.Generic.List`1 => system-collections-generic-list-1
      Options: (none)
    System.Collections.Generic.SortedList`2 => system-collections-generic-sorted-list-2
      Options: --defgeneric
  System.Numerics.Vectors.dll
    System.Numerics.Vector2 => system-numerics-vector2
      Constant properties: *
      Options: (none)
    System.Numerics.Vector3 => system-numerics-vector3
      Constant properties: *
      Options: --defgeneric
    System.Numerics.Vector4 => system-numerics-vector4
      Constant properties: *
      Options: --defgeneric
  System.Threading.Timer.dll
    System.Threading.Timer => system-threading-timer
      Options: --defgeneric --ensure-type --ensure-type-in-generic
  System.ComponentModel.TypeConverter.dll
    System.Timers.Timer => system-timers-timer
      Options: --defgeneric
  System.Diagnostics.Debug.dll
    System.Diagnostics.Debug => system-diagnostics-debug
      Options: (none)
  System.Globalization.dll
    System.Globalization.CultureInfo => system-globalization-culture-info
      Options: (none)
  System.Net.ServicePoint.dll
    System.Net.ServicePointManager => system-net-service-point-manager
      Options: (none)
  System.Runtime.Extensions.dll
    System.Environment => system-environment
      Options: (none)
    System.AppDomain => system-app-domain
      Options: (none)
  System.Threading.Thread.dll
    System.Threading.Thread => system-threading-thread
      Options: (none)
  System.Collections.Specialized.dll
    System.Collections.Specialized.NameValueCollection => system-collections-specialized-name-value-collection
      Options: --export-interfaces --export-object --export-parents
    System.Collections.Specialized.NameObjectCollectionBase => system-collections-specialized-name-object-collection-base
      Options: --export-interfaces --export-object --export-parents
      Discovered via: --export-parents/--export-interfaces from System.Collections.Specialized.NameValueCollection
  AssemblyToLispyTestTarget.dll
    AssemblyToLispyTestTarget.EventTestClass => assembly-to-lispy-test-target-event-test-class
      Options: (none)
    AssemblyToLispyTestTarget.NestingContainer => assembly-to-lispy-test-target-nesting-container
      Options: --output-nested
    AssemblyToLispyTestTarget.AbstractBase => assembly-to-lispy-test-target-abstract-base
      Options: --output-children
    AssemblyToLispyTestTarget.IDummyInterface => assembly-to-lispy-test-target-i-dummy-interface
      Options: --output-implementations
    AssemblyToLispyTestTarget.ConcreteDerivedFromGeneric => assembly-to-lispy-test-target-concrete-derived-from-generic
      Options: --export-parents
    AssemblyToLispyTestTarget.ObsoleteType => assembly-to-lispy-test-target-obsolete-type
      Options: (none)
    AssemblyToLispyTestTarget.ObsoleteAndTupleFixtures => assembly-to-lispy-test-target-obsolete-and-tuple-fixtures
      Options: (none)
    AssemblyToLispyTestTarget.SubSpace.SubSpaceClassOne => assembly-to-lispy-test-target-sub-space-sub-space-class-one
      Options: --defgeneric
    AssemblyToLispyTestTarget.SubSpace.SubSpaceClassTwo => assembly-to-lispy-test-target-sub-space-sub-space-class-two
      Options: --defgeneric
    AssemblyToLispyTestTarget.NestingContainer+NestedLevel2 => assembly-to-lispy-test-target-nesting-container-nested-level2
      Options: --output-nested
      Discovered via: --output-nested from AssemblyToLispyTestTarget.NestingContainer
    AssemblyToLispyTestTarget.NestingContainer+NestedLevel2+NestedLevel3 => assembly-to-lispy-test-target-nesting-container-nested-level2-nested-level3
      Options: --output-nested
      Discovered via: --output-nested from AssemblyToLispyTestTarget.NestingContainer
    AssemblyToLispyTestTarget.GenericClass`1 => assembly-to-lispy-test-target-generic-class-1
      Options: --output-children
      Discovered via: --output-children from AssemblyToLispyTestTarget.AbstractBase
    AssemblyToLispyTestTarget.GenericBaseForSuperclassTest`1 => assembly-to-lispy-test-target-generic-base-for-superclass-test-1
      Options: --export-parents
      Discovered via: --export-parents from AssemblyToLispyTestTarget.ConcreteDerivedFromGeneric
"
  :components (
   (:file "packages")
   (:file "csharp-assembly-utils" :depends-on ("packages"))
   (:file "system-console" :depends-on ("packages" "csharp-assembly-utils"))
   (:file "system-time-span" :depends-on ("packages" "csharp-assembly-utils"))
   (:file "system-object" :depends-on ("packages" "csharp-assembly-utils"))
   (:file "system-type" :depends-on ("packages" "csharp-assembly-utils"))
   (:file "system-string" :depends-on ("packages" "csharp-assembly-utils"))
   (:file "system-array" :depends-on ("packages" "csharp-assembly-utils"))
   (:file "system-time-zone-info" :depends-on ("packages" "csharp-assembly-utils"))
   (:file "system-convert" :depends-on ("packages" "csharp-assembly-utils"))
   (:file "system-text-string-builder" :depends-on ("packages" "csharp-assembly-utils"))
   (:file "system-time-zone-info-adjustment-rule" :depends-on ("packages" "csharp-assembly-utils"))
   (:file "system-value-tuple-2" :depends-on ("packages" "csharp-assembly-utils" "system-collections-i-structural-comparable" "system-collections-i-structural-equatable" "system-i-comparable" "system-i-comparable-1" "system-i-equatable-1" "system-runtime-compiler-services-i-tuple"))
   (:file "system-value-tuple-3" :depends-on ("packages" "csharp-assembly-utils"))
   (:file "system-value-tuple-4" :depends-on ("packages" "csharp-assembly-utils"))
   (:file "system-value-tuple-5" :depends-on ("packages" "csharp-assembly-utils"))
   (:file "system-value-tuple-6" :depends-on ("packages" "csharp-assembly-utils"))
   (:file "system-value-tuple-7" :depends-on ("packages" "csharp-assembly-utils"))
   (:file "system-value-tuple-8" :depends-on ("packages" "csharp-assembly-utils"))
   (:file "system-argument-out-of-range-exception" :depends-on ("packages" "csharp-assembly-utils" "system-argument-exception" "system-runtime-serialization-i-serializable" "system-system-exception" "system-exception" "system-object"))
   (:file "system-collections-hashtable" :depends-on ("packages" "csharp-assembly-utils"))
   (:file "system-io-memory-stream" :depends-on ("packages" "csharp-assembly-utils" "system-io-stream" "system-i-async-disposable" "system-i-disposable" "system-marshal-by-ref-object" "system-object"))
   (:file "system-io-stream-reader" :depends-on ("packages" "csharp-assembly-utils" "system-io-text-reader" "system-i-disposable" "system-marshal-by-ref-object"))
   (:file "system-collections-i-structural-comparable" :depends-on ("packages" "csharp-assembly-utils"))
   (:file "system-collections-i-structural-equatable" :depends-on ("packages" "csharp-assembly-utils"))
   (:file "system-i-comparable" :depends-on ("packages" "csharp-assembly-utils"))
   (:file "system-i-comparable-1" :depends-on ("packages" "csharp-assembly-utils"))
   (:file "system-i-equatable-1" :depends-on ("packages" "csharp-assembly-utils"))
   (:file "system-runtime-compiler-services-i-tuple" :depends-on ("packages" "csharp-assembly-utils"))
   (:file "system-argument-exception" :depends-on ("packages" "csharp-assembly-utils" "system-system-exception" "system-runtime-serialization-i-serializable" "system-exception" "system-object"))
   (:file "system-runtime-serialization-i-serializable" :depends-on ("packages" "csharp-assembly-utils"))
   (:file "system-system-exception" :depends-on ("packages" "csharp-assembly-utils" "system-exception" "system-runtime-serialization-i-serializable" "system-object"))
   (:file "system-exception" :depends-on ("packages" "csharp-assembly-utils" "system-object" "system-runtime-serialization-i-serializable"))
   (:file "system-io-stream" :depends-on ("packages" "csharp-assembly-utils" "system-marshal-by-ref-object" "system-i-async-disposable" "system-i-disposable" "system-object"))
   (:file "system-i-async-disposable" :depends-on ("packages" "csharp-assembly-utils"))
   (:file "system-i-disposable" :depends-on ("packages" "csharp-assembly-utils"))
   (:file "system-marshal-by-ref-object" :depends-on ("packages" "csharp-assembly-utils" "system-object"))
   (:file "system-io-text-reader" :depends-on ("packages" "csharp-assembly-utils" "system-marshal-by-ref-object" "system-i-disposable"))
   (:file "system-collections-i-collection" :depends-on ("packages" "csharp-assembly-utils" "system-collections-i-enumerable"))
   (:file "system-collections-i-enumerable" :depends-on ("packages" "csharp-assembly-utils"))
   (:file "system-runtime-serialization-i-deserialization-callback" :depends-on ("packages" "csharp-assembly-utils"))
   (:file "system-linq-enumerable" :depends-on ("packages" "csharp-assembly-utils"))
   (:file "system-xml-xml-reader" :depends-on ("packages" "csharp-assembly-utils" "system-i-disposable"))
   (:file "system-collections-generic-dictionary-2" :depends-on ("packages" "csharp-assembly-utils"))
   (:file "system-collections-generic-dictionary-2-key-collection" :depends-on ("packages" "csharp-assembly-utils"))
   (:file "system-collections-generic-dictionary-2-value-collection" :depends-on ("packages" "csharp-assembly-utils"))
   (:file "system-collections-generic-list-1" :depends-on ("packages" "csharp-assembly-utils"))
   (:file "system-collections-generic-sorted-list-2" :depends-on ("packages" "csharp-assembly-utils"))
   (:file "system-numerics-vector2" :depends-on ("packages" "csharp-assembly-utils"))
   (:file "system-numerics-vector3" :depends-on ("packages" "csharp-assembly-utils"))
   (:file "system-numerics-vector4" :depends-on ("packages" "csharp-assembly-utils"))
   (:file "system-threading-timer" :depends-on ("packages" "csharp-assembly-utils"))
   (:file "system-timers-timer" :depends-on ("packages" "csharp-assembly-utils"))
   (:file "system-diagnostics-debug" :depends-on ("packages" "csharp-assembly-utils"))
   (:file "system-globalization-culture-info" :depends-on ("packages" "csharp-assembly-utils"))
   (:file "system-net-service-point-manager" :depends-on ("packages" "csharp-assembly-utils"))
   (:file "system-environment" :depends-on ("packages" "csharp-assembly-utils"))
   (:file "system-app-domain" :depends-on ("packages" "csharp-assembly-utils"))
   (:file "system-threading-thread" :depends-on ("packages" "csharp-assembly-utils"))
   (:file "system-collections-specialized-name-value-collection" :depends-on ("packages" "csharp-assembly-utils" "system-collections-specialized-name-object-collection-base" "system-collections-i-collection" "system-collections-i-enumerable" "system-runtime-serialization-i-deserialization-callback" "system-runtime-serialization-i-serializable" "system-object"))
   (:file "system-collections-specialized-name-object-collection-base" :depends-on ("packages" "csharp-assembly-utils" "system-object" "system-collections-i-collection" "system-collections-i-enumerable" "system-runtime-serialization-i-deserialization-callback" "system-runtime-serialization-i-serializable"))
   (:file "assembly-to-lispy-test-target-event-test-class" :depends-on ("packages" "csharp-assembly-utils"))
   (:file "assembly-to-lispy-test-target-nesting-container" :depends-on ("packages" "csharp-assembly-utils"))
   (:file "assembly-to-lispy-test-target-abstract-base" :depends-on ("packages" "csharp-assembly-utils"))
   (:file "assembly-to-lispy-test-target-i-dummy-interface" :depends-on ("packages" "csharp-assembly-utils"))
   (:file "assembly-to-lispy-test-target-concrete-derived-from-generic" :depends-on ("packages" "csharp-assembly-utils" "assembly-to-lispy-test-target-generic-base-for-superclass-test-1" "system-collections-generic-list-1"))
   (:file "assembly-to-lispy-test-target-obsolete-type" :depends-on ("packages" "csharp-assembly-utils"))
   (:file "assembly-to-lispy-test-target-obsolete-and-tuple-fixtures" :depends-on ("packages" "csharp-assembly-utils"))
   (:file "assembly-to-lispy-test-target-sub-space-sub-space-class-one" :depends-on ("packages" "csharp-assembly-utils"))
   (:file "assembly-to-lispy-test-target-sub-space-sub-space-class-two" :depends-on ("packages" "csharp-assembly-utils"))
   (:file "assembly-to-lispy-test-target-nesting-container-nested-level2" :depends-on ("packages" "csharp-assembly-utils"))
   (:file "assembly-to-lispy-test-target-nesting-container-nested-level2-nested-level3" :depends-on ("packages" "csharp-assembly-utils"))
   (:file "assembly-to-lispy-test-target-generic-class-1" :depends-on ("packages" "csharp-assembly-utils"))
   (:file "assembly-to-lispy-test-target-generic-base-for-superclass-test-1" :depends-on ("packages" "csharp-assembly-utils" "system-collections-generic-list-1"))
   ;; csharp-generics.lisp is NOT included above as a :components entry
   ;; (--no-csharp-generic-in-asd): #.(dotnet:class-for-type ...) inside it
   ;; resolves .NET types at COMPILE time, unlike every other file in
   ;; this system, which can fail if this whole system is loaded via
   ;; ASDF :depends-on before the consuming project's own target
   ;; assembly is in scope (see doc/generator-design-notes.md's
   ;; Version 41/46 sections and dotcl/dotcl#49). To use
   ;; --defgeneric-generated dispatch, splice the commented-out
   ;; component below into the CONSUMING project's own .asd
   ;; :components list instead, at a point after its own assembly
   ;; references are already loaded:
   ;; (:file "csharp-generics" :depends-on ("packages" "csharp-assembly-utils" "system-object" "system-string" "system-array" "system-text-string-builder" "system-collections-generic-dictionary-2" "system-collections-generic-sorted-list-2" "system-numerics-vector3" "system-numerics-vector4" "system-threading-timer" "system-timers-timer" "assembly-to-lispy-test-target-sub-space-sub-space-class-one" "assembly-to-lispy-test-target-sub-space-sub-space-class-two"))
  ))
